"""RT-3.1, part C: the guidance pass, and GI moved onto it.

The guidance target is built once per distinct divisor -- GI and AO can be on
different rungs (GI half or quarter by its detail dial, AO half or quarter by
its own) and a scene using both at the same rung should pay for one downsample,
not two.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rep import read, write, rep, has

F = 'RageV/src/RageV/Renderer/FrameGraphBuilder.cpp'
s = read(F)
if has(s, 'auto guidanceFor'):
    print('FrameGraphBuilder.cpp already has guidanceFor')
    raise SystemExit(0)

# --- the builder, right after addSignal ----------------------------------
s = rep(s,
    "\t\t\t\tblurInput = output;\n"
    "\t\t\t\tblurred = output;\n"
    "\t\t\t}\n"
    "\t\t\treturn blurred;\n"
    "\t\t};\n",
    "\t\t\t\tblurInput = output;\n"
    "\t\t\t\tblurred = output;\n"
    "\t\t\t}\n"
    "\t\t\treturn blurred;\n"
    "\t\t};\n"
    "\t\t// **RT-3.1: the guidance lanes at a divisor, built once and shared.** GI\n"
    "\t\t// and the occlusion can sit on different rungs of their own dials; two\n"
    "\t\t// signals on the same rung should pay for one downsample between them.\n"
    "\t\t// Keyed by divisor, and the pass is added the first time one is asked for,\n"
    "\t\t// so a frame with no reduced-resolution signal adds nothing at all.\n"
    "\t\tstd::map<uint32_t, SignalGuidance> guidanceCache;\n"
    "\t\tauto guidanceFor = [&](uint32_t divisor) -> SignalGuidance\n"
    "\t\t{\n"
    "\t\t\tif (divisor <= 1 || !PostProcess::IsReady())\n"
    "\t\t\t\treturn {};\n"
    "\t\t\tconst auto found = guidanceCache.find(divisor);\n"
    "\t\t\tif (found != guidanceCache.end())\n"
    "\t\t\t\treturn found->second;\n"
    "\n"
    "\t\t\tRGTargetDesc guideDesc;\n"
    "\t\t\tguideDesc.Name = \"Guidance\";\n"
    "\t\t\t// Depth in full precision: it is fed straight to the inverse\n"
    "\t\t\t// view-projection, and a half float near the far plane rebuilds a\n"
    "\t\t\t// position metres from where the surface is.\n"
    "\t\t\tguideDesc.Color = Format::R32_SFLOAT;\n"
    "\t\t\tguideDesc.ExtraColors = { kNormalFormat, Format::R16G16_SFLOAT };\n"
    "\t\t\tguideDesc.Depth = Format::Undefined;\n"
    "\t\t\tguideDesc.Scale = 1.0f / (float)divisor;\n"
    "\t\t\tconst RGResource guide = graph.CreateTarget(guideDesc);\n"
    "\n"
    "\t\t\tgraph.AddPass(\"Guidance downsample\",\n"
    "\t\t\t\t[&](RGPassBuilder& builder)\n"
    "\t\t\t\t{\n"
    "\t\t\t\t\tbuilder.Write(guide);\n"
    "\t\t\t\t\tbuilder.Sample(sceneHDR);\n"
    "\t\t\t\t\tbuilder.DisableDepth();\n"
    "\t\t\t\t},\n"
    "\t\t\t\t[sceneHDR, normalIndex, velocityIndex, divisor](RGPassContext& context)\n"
    "\t\t\t\t{\n"
    "\t\t\t\t\tPostProcess::GuideDownsample(context.Cmd,\n"
    "\t\t\t\t\t\t\t\t\t\t\t\t context.Depth(sceneHDR),\n"
    "\t\t\t\t\t\t\t\t\t\t\t\t context.Color(sceneHDR, normalIndex),\n"
    "\t\t\t\t\t\t\t\t\t\t\t\t context.Color(sceneHDR, velocityIndex),\n"
    "\t\t\t\t\t\t\t\t\t\t\t\t divisor, Format::R32_SFLOAT,\n"
    "\t\t\t\t\t\t\t\t\t\t\t\t kNormalFormat, Format::R16G16_SFLOAT);\n"
    "\t\t\t\t});\n"
    "\n"
    "\t\t\tSignalGuidance made;\n"
    "\t\t\tmade.Depth = guide;\n"
    "\t\t\tmade.Surface = guide;\n"
    "\t\t\tmade.Velocity = guide;\n"
    "\t\t\tmade.Divisor = divisor;\n"
    "\t\t\tguidanceCache.emplace(divisor, made);\n"
    "\t\t\treturn made;\n"
    "\t\t};\n")

# --- GI: contract at the trace's resolution, upsample last ---------------
s = rep(s,
    "\t\t\tRGTargetDesc giDesc;\n"
    "\t\t\tgiDesc.Name = \"GiFresh\";\n"
    "\t\t\tgiDesc.Color = Format::R16G16B16A16_SFLOAT;\n"
    "\t\t\tgiDesc.Depth = Format::Undefined;\n"
    "\t\t\tgiDesc.Scale = (float)supersample;\n"
    "\t\t\tconst RGResource giFresh = graph.CreateTarget(giDesc);\n"
    "\t\t\tgraph.AddPass(\"GI upsample\",\n"
    "\t\t\t\t[&](RGPassBuilder& builder)\n"
    "\t\t\t\t{\n"
    "\t\t\t\t\tbuilder.Write(giFresh);\n"
    "\t\t\t\t\tbuilder.Sample(giRaw);\n"
    "\t\t\t\t\tbuilder.Sample(sceneHDR);\n"
    "\t\t\t\t\tbuilder.DisableDepth();\n"
    "\t\t\t\t},\n"
    "\t\t\t\t[giRaw, sceneHDR, giTraceWidth, giTraceHeight,\n"
    "\t\t\t\t nearZ = desc.NearClip, farZ = desc.FarClip](RGPassContext& context)\n"
    "\t\t\t\t{\n"
    "\t\t\t\t\tPostProcess::GiUpsample(context.Cmd, context.Color(giRaw),\n"
    "\t\t\t\t\t\t\t\t\t\t\tcontext.Depth(sceneHDR),\n"
    "\t\t\t\t\t\t\t\t\t\t\tgiTraceWidth, giTraceHeight, nearZ, farZ,\n"
    "\t\t\t\t\t\t\t\t\t\t\tFormat::R16G16B16A16_SFLOAT);\n"
    "\t\t\t\t});\n"
    "\n"
    "\t\t\tgiLit = giFresh;\n"
    "\t\t\tTemporalHistory& gi = *desc.GiLight;\n"
    "\t\t\tgi.Prepare(Renderer::GetDevice(),\n"
    "\t\t\t\t\t   desc.Width * (uint32_t)supersample, desc.Height * (uint32_t)supersample,\n"
    "\t\t\t\t\t   Format::R16G16B16A16_SFLOAT, \"GiSignal\",\n"
    "\t\t\t\t\t   Format::R16G16B16A16_SFLOAT, Format::R16G16B16A16_SFLOAT);\n"
    "\t\t\tif (gi.Current() && gi.Previous())\n"
    "\t\t\t{\n"
    "\t\t\t\tconst RGResource previousGi = graph.Import(gi.Previous(), \"GiPrevious\");\n"
    "\t\t\t\tcurrentGi = graph.Import(gi.Current(), \"GiCurrent\");\n"
    "\t\t\t\tRGTargetDesc giBlurDesc = giDesc;\n"
    "\t\t\t\tgiBlurDesc.Name = \"GiBlurred\";\n"
    "\t\t\t\tstatic const SignalPassNames kGiPasses =\n"
    "\t\t\t\t\t{ \"GiAccumulate\", { \"GiBlur\", \"GiBlur2\", \"GiBlur4\" } };\n"
    "\t\t\t\tgiLit = addSignal(kGiPasses, Renderer3D::GiSignal(),\n"
    "\t\t\t\t\t\t\t\t  giFresh, currentGi, previousGi, gi.HasHistory(),\n"
    "\t\t\t\t\t\t\t\t  &gi.Motion(), giBlurDesc, false);\n"
    "\t\t\t\tgi.Advance();\n"
    "\t\t\t}\n"
    "\t\t}\n",
    "\t\t\t// **RT-3.1: the contract runs here, at the trace's own resolution.**\n"
    "\t\t\t// It used to run after a full-resolution upsample, which paid four\n"
    "\t\t\t// times the texels for a signal that carries information at one in\n"
    "\t\t\t// four -- 0.85 ms of RT-3's 0.89 ms chain. Filtering where the signal\n"
    "\t\t\t// was traced and upsampling once at the end is the arrangement every\n"
    "\t\t\t// real-time denoiser uses, and the guidance downsample above is what\n"
    "\t\t\t// keeps the contract's surface tests honest on the coarser grid.\n"
    "\t\t\tRGTargetDesc giDesc = giRawDesc;\n"
    "\t\t\tgiDesc.Name = \"GiSettled\";\n"
    "\t\t\tRGResource giSettled = giRaw;\n"
    "\t\t\tTemporalHistory& gi = *desc.GiLight;\n"
    "\t\t\tgi.Prepare(Renderer::GetDevice(), giTraceWidth, giTraceHeight,\n"
    "\t\t\t\t\t   Format::R16G16B16A16_SFLOAT, \"GiSignal\",\n"
    "\t\t\t\t\t   Format::R16G16B16A16_SFLOAT, Format::R16G16B16A16_SFLOAT);\n"
    "\t\t\tif (gi.Current() && gi.Previous())\n"
    "\t\t\t{\n"
    "\t\t\t\tconst RGResource previousGi = graph.Import(gi.Previous(), \"GiPrevious\");\n"
    "\t\t\t\tcurrentGi = graph.Import(gi.Current(), \"GiCurrent\");\n"
    "\t\t\t\tRGTargetDesc giBlurDesc = giDesc;\n"
    "\t\t\t\tgiBlurDesc.Name = \"GiBlurred\";\n"
    "\t\t\t\tstatic const SignalPassNames kGiPasses =\n"
    "\t\t\t\t\t{ \"GiAccumulate\", { \"GiBlur\", \"GiBlur2\", \"GiBlur4\" } };\n"
    "\t\t\t\tgiSettled = addSignal(kGiPasses, Renderer3D::GiSignal(),\n"
    "\t\t\t\t\t\t\t\t\t  giRaw, currentGi, previousGi, gi.HasHistory(),\n"
    "\t\t\t\t\t\t\t\t\t  &gi.Motion(), giBlurDesc, false,\n"
    "\t\t\t\t\t\t\t\t\t  guidanceFor(giDivisor));\n"
    "\t\t\t\tgi.Advance();\n"
    "\t\t\t}\n"
    "\n"
    "\t\t\t// And one joint bilateral upsample at the end, onto the lit pass's\n"
    "\t\t\t// grid, which is the only place the lit shader can read it by texel.\n"
    "\t\t\tRGTargetDesc giFullDesc;\n"
    "\t\t\tgiFullDesc.Name = \"GiFull\";\n"
    "\t\t\tgiFullDesc.Color = Format::R16G16B16A16_SFLOAT;\n"
    "\t\t\tgiFullDesc.Depth = Format::Undefined;\n"
    "\t\t\tgiFullDesc.Scale = (float)supersample;\n"
    "\t\t\tconst RGResource giFull = graph.CreateTarget(giFullDesc);\n"
    "\t\t\tgraph.AddPass(\"GI upsample\",\n"
    "\t\t\t\t[&](RGPassBuilder& builder)\n"
    "\t\t\t\t{\n"
    "\t\t\t\t\tbuilder.Write(giFull);\n"
    "\t\t\t\t\tbuilder.Sample(giSettled);\n"
    "\t\t\t\t\tbuilder.Sample(sceneHDR);\n"
    "\t\t\t\t\tbuilder.DisableDepth();\n"
    "\t\t\t\t},\n"
    "\t\t\t\t[giSettled, sceneHDR, giTraceWidth, giTraceHeight,\n"
    "\t\t\t\t nearZ = desc.NearClip, farZ = desc.FarClip](RGPassContext& context)\n"
    "\t\t\t\t{\n"
    "\t\t\t\t\tPostProcess::GiUpsample(context.Cmd, context.Color(giSettled),\n"
    "\t\t\t\t\t\t\t\t\t\t\tcontext.Depth(sceneHDR),\n"
    "\t\t\t\t\t\t\t\t\t\t\tgiTraceWidth, giTraceHeight, nearZ, farZ,\n"
    "\t\t\t\t\t\t\t\t\t\t\tFormat::R16G16B16A16_SFLOAT);\n"
    "\t\t\t\t});\n"
    "\t\t\tgiLit = giFull;\n"
    "\t\t}\n")

write(F, s)
print('FrameGraphBuilder.cpp: guidance pass added, GI moved to half resolution')
