#!/usr/bin/env python3
"""Build the camp scene: a forest clearing at night, and a camera that shows it.

    python tools/scripts/make_camp_textures.py
    python tools/scripts/make_camp_models.py
    python tools/scripts/check_models.py
    python tools/scripts/make_camp_scene.py

**The place.** A clearing in a pine forest, well after sunset. A ridge tent
pitched on the flat ground at one side. A fire burning down inside a ring of
stones, with the wood for it stacked beside. Folding chairs facing it, one
pushed back. A fallen trunk somebody has been sitting on. A case, a bedroll and
a pack. A mirror on its kickstand, angled at the fire. A fox at the treeline and
three rabbits that have come closer than they should have.

Everything below is in that description, and the description is the argument for
it. The rule the courtyard scene set holds here: **nothing goes in because it is
new -- it goes in because the place would have one.**

| The clearing has | Which exercises |
|---|---|
| Sculpted ground | Terrain: heightfield, layered materials, LOD chunks |
| A hundred pines, stones and tufts | FBX import, and instanced draws -- one mesh, many entities |
| A tent, chairs, a case, a cooler | More FBX, and the flat-shaded low-poly look |
| A fox at the treeline | glTF import, skinning, an animation clip |
| A mirror on a kickstand | A realtime probe, screen-space reflections and traced ones |
| A fire | Modelled flame, additive embers, a light that flickers, looping audio |
| Night | A dark sky, a moon, a dusk rim behind the trees, and post that earns it |
| A camera that moves | Five framed shots as entities, and a script that eases between them |

**Composition, since it is the actual subject.** The reference is a photograph
of a model, and what makes it work is four things a bright scene cannot have:

  * **One focal point, and it is the brightest thing.** The fire. Nothing else
    in the frame comes near it in value.
  * **Value separates depth.** Dark foreground, lit camp, dark treeline against
    a slightly lighter sky. Three bands the eye reads as distance -- and the
    first version had all three at the same brightness, which is why it read
    flat.
  * **The frame is framed.** Big trees at the edges, nearer and darker.
  * **Lines lead in.** The log points at the fire, the chairs face it, the
    forks reach into it.

**The light's range matters more than its intensity.** A light whose reach
exceeds the scene has no falloff inside the frame, and falloff is what makes a
fire look like a fire rather than a floodlight with a warm gel. The fire here
reaches nine metres, which ends at the chairs and leaves the treeline dark.

**Nothing here is borrowed from the courtyard.** Its own maps, its own flame
sprite, its own grade, its own curves, its own fire loop -- all generated by
`make_camp_textures.py` and by this file. The single exception is the fox,
which is the only rigged and animated asset the project has and is low-poly
already; it keeps its own glTF material and texture.
"""

import argparse
import math
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import postprofile                                              # noqa: E402
import make_terrain                                             # noqa: E402
from make_demo_scene import Scene, handle_for, vec, write_material  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
ASSETS = ROOT / "SampleProject" / "assets"

# SceneSerializer::kVersion. Written explicitly because the default is 1 and
# the difference is whether entity ids -- and therefore parenting -- survive.
SCENE_VERSION = 6

# Where the van is parked. Named up here because the forest has to be told to
# keep out of it as well -- a scattered pine will happily stand in a van.
VAN_AT = (-5.9, -3.3)

PRIMITIVE_BASE = 0x7261676556000000
CUBE, SPHERE, PLANE, CYLINDER, QUAD = (PRIMITIVE_BASE + i for i in range(5))

# The fox, which is the courtyard's too. Kept deliberately: it is the only
# rigged, animated, low-poly asset in the project, and a scene about showing
# the engine off with nothing alive in it is a diorama.
MESH_FOX = 11679010045657754579
MAT_FOX = 14845622431998451938

# The ground. `clearing` is level in the middle and lifts into forest at the
# edges; `hills` was tried first and put the tent inside a hillside, because a
# landscape has no flat part and a camp needs one.
TERRAIN_SIZE = 190.0
TERRAIN_HEIGHT = 30.0
# The clearing's flat part sits at 8 % of full height, so dropping the terrain
# by that much puts the camp floor at y = 0 and lets every prop be placed at
# the height it actually is.
TERRAIN_Y = -0.08 * TERRAIN_HEIGHT


# --- handles ------------------------------------------------------------------
#
# Read from the `.meta` files the registry minted, never pasted. This scene is
# regenerated every time a model changes, and a table of handles copied by hand
# is a table that goes stale exactly when it matters.

def read_handle(path):
    path = pathlib.Path(path)
    if not path.exists():
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("Handle:"):
            return int(line.split(":", 1)[1].strip())
    return None


def handles_in(directory, suffix, strip):
    found = {}
    for meta in sorted(pathlib.Path(directory).glob("*" + suffix + ".meta")):
        handle = read_handle(meta)
        if handle:
            found[meta.name[:-len(suffix) - len(".meta")].replace(strip, "", 1)] = handle
    return found


def require(table, *names):
    missing = [name for name in names if name not in table]
    if missing:
        raise SystemExit(
            "no handle yet for: " + ", ".join(missing) + "\n"
            "Run the generators, then the engine once so the registry mints "
            "them, then this again.")


# --- the ground ---------------------------------------------------------------

_HEIGHTS = None


def ground_height(x, z):
    """The clearing's surface at a world point, in metres.

    **Props are placed on the ground rather than at zero.** The clearing is
    level for sixteen metres and then lifts, so a tree at twenty metres placed
    at y = 0 is buried half a metre and one at thirty is buried two. Sampling
    the same heightfield the terrain asset was written from is the only way for
    the two to agree; guessing an offset per ring is how a forest ends up
    standing on a staircase.
    """
    global _HEIGHTS
    if _HEIGHTS is None:
        _HEIGHTS = make_terrain.clearing()

    size = _HEIGHTS.shape[0]
    u = (x / TERRAIN_SIZE + 0.5) * (size - 1)
    v = (z / TERRAIN_SIZE + 0.5) * (size - 1)

    u = min(max(u, 0.0), size - 1.001)
    v = min(max(v, 0.0), size - 1.001)

    x0, z0 = int(u), int(v)
    fx, fz = u - x0, v - z0

    def at(row, col):
        return _HEIGHTS[row, col] / 65535.0

    top = at(z0, x0) * (1 - fx) + at(z0, x0 + 1) * fx
    bottom = at(z0 + 1, x0) * (1 - fx) + at(z0 + 1, x0 + 1) * fx
    unit = top * (1 - fz) + bottom * fz

    return TERRAIN_Y + unit * TERRAIN_HEIGHT


def scatter(seed, count, inner, outer):
    """Points in a ring, from a fixed sequence.

    A hash rather than `random`: the scene has to regenerate identically or
    every run is a diff, and a seeded generator whose implementation can change
    between Python versions is not a guarantee.

    The radius is spread by its square root, so the points are even per unit of
    *area* rather than per unit of radius -- without it everything bunches at
    the inner edge, which is what a ring of trees must not do.
    """
    points = []
    for i in range(count):
        h = (seed * 6364136223846793005 + i * 1442695040888963407) & 0xFFFFFFFF
        angle = (h % 10000) / 10000.0 * math.tau
        spread = ((h >> 13) % 10000) / 10000.0
        radius = math.sqrt(inner * inner + spread * (outer * outer - inner * inner))
        spin = ((h >> 7) % 10000) / 10000.0 * math.tau
        size = 0.78 + ((h >> 19) % 10000) / 10000.0 * 0.55
        points.append((math.cos(angle) * radius, math.sin(angle) * radius,
                       spin, size))
    return points


# --- the camera ---------------------------------------------------------------
#
# Five shots, each written as a target, a distance and two angles -- which is
# how a shot is actually chosen -- and solved into a position here. A position
# and an euler triple typed in directly is a number nobody can adjust, because
# moving the camera closer means recomputing all three.
#
# The shots go into the scene as entities the script reads, so they are visible
# and movable in the editor rather than compiled into a script.

# (name, target, distance, yaw degrees, pitch degrees)
#
# Twelve, and the order is the film. Consecutive shots that share a target and a
# distance and differ only in yaw give a **lateral move**: the script eases
# between two points on the same circle, which reads as the camera tracking
# sideways past the camp rather than cutting to another side of it. Shots 1-2
# and 6-7 are those pairs, and they are the two moments the scene shows that it
# has depth rather than asserting it.
#
# Twelve rather than eight because the first set never went *close* to
# anything: the tent's doorway and the mirror are the two props with the most
# work in them and both were only ever seen from six metres.
SHOTS = (
    # 1-2. The establishing view -- the reference's: high, three-quarter,
    #      looking down about thirty degrees -- and then a track across the
    #      front of the camp at the same height.
    ("Shot 1", (0.5, 0.7, 0.0), 7.8, 26.0, -30.0),
    ("Shot 2", (0.5, 0.7, 0.0), 7.4, -16.0, -27.0),
    # 3. Down low across the fire, which is the shot that shows what a light
    #    with real falloff does. Pulled in from 4.3 m, where the camera stood
    #    on the inner edge of the sapling ring and clipped one.
    ("Shot 3", (1.1, 0.65, -0.6), 3.6, -6.0, -8.0),
    # 4. **The doorway, close.** Three metres from the tent's opening, which is
    #    the one genuinely dark place in the scene.
    #
    #    Not square on to it, and that is not a stylistic choice: the tent's
    #    door faces the fire by design, so a camera placed straight out from
    #    the doorway stands *in* the fire -- which is exactly where the first
    #    solve put it, 18 cm from the origin. Off to one side by forty degrees
    #    keeps the doorway readable and puts the firelight in the near corner
    #    of frame instead of in the lens.
    ("Shot 4", (1.87, 1.0, -1.58), 3.0, -12.0, -6.0),
    # 5. And back out to the tent's three-quarter. Yaw *positive*: at -48 the
    #    solve stood the camera in the fire.
    ("Shot 5", (3.0, 1.05, -2.4), 5.2, 52.0, -12.0),
    # 6-7. Behind the camp looking back, and a track left along it -- the
    #      second lateral, and the one that puts the van and the mirror in
    #      frame together.
    ("Shot 6", (0.4, 1.0, -1.2), 6.6, 152.0, -13.0),
    ("Shot 7", (-1.6, 1.0, -1.4), 6.2, 205.0, -11.0),
    # 8. The van from outside the clearing, looking back in past it. The only
    #    shot that faces inward, and the one that says how big the clearing is.
    ("Shot 8", (-5.9, 1.1, -3.3), 5.0, 250.0, -8.0),
    # 9-10. The mirror in context, and then **the mirror close**, where the
    #       reflection fills a third of the frame. This is the pair the probe,
    #       the screen-space pass and the traced pass are all for -- at six
    #       metres their differences are a few pixels, and at one metre they
    #       are the subject.
    ("Shot 9", (-2.5, 0.9, 0.3), 4.2, 74.0, -8.0),
    #       Twice the distance it started at, and swung round to sixty degrees
    #       to get it. Backing straight off the glass does not work: the mirror
    #       faces the fire on purpose, so the camera reverses along the mirror's
    #       normal and ends up standing *in* the fire, which the shot check
    #       says so in as many words.
    ("Shot 10", (-2.55, 0.85, 0.42), 2.3, 60.0, -5.0),
    # 11. A slow push toward the fox at the treeline, ending on the one thing
    #     here that is alive.
    ("Shot 11", (4.0, 0.45, 2.0), 3.4, 40.0, -9.0),
    # 12. And out to a last wide from the other side, so the film ends where it
    #     began without repeating the frame it began on.
    ("Shot 12", (0.6, 0.9, 0.2), 9.6, -50.0, -26.0),
)



# **One focus distance cannot serve twelve shots.** They range from 2.3 m -- the
# mirror, close -- to 9.6 m at the final wide, and a single value leaves either
# the close shots blurred at the front or the wides blurred at the subject. The
# fox's own closing shot came back as a soft orange smear with an unreadable
# name tag, which is the shot the whole film ends on.
#
# So the camera changes focus per shot, and **the script carries the table**:
# one field on CampCamera holding the profile each shot wants, in shot order,
# written here so the two cannot drift.
#
# It used to be a CameraComponent on every marker, ViewRank 90 so none of them
# could ever become primary, and the script read each marker's profile off it.
# That worked and it cost the scene twelve cameras to hold twelve numbers --
# a whole component, with a projection and clip planes and an aspect flag, per
# marker, none of which was ever rendered through. A scene that reports
# thirteen cameras when it has one is a scene that is lying about itself.
#
# Four bands rather than twelve profiles: focus is a soft quantity and the
# difference between 3.4 m and 3.6 m is not visible, while four small files are
# four things to keep track of instead of twelve.
FOCUS_BANDS = (2.6, 3.6, 5.4, 8.4)


def focus_band(distance):
    """The band nearest a subject distance."""
    return min(FOCUS_BANDS, key=lambda band: abs(band - distance))


def segment_distance(point, a, b):
    """Distance from a point to a line segment, in the ground plane."""
    ax, az = a
    bx, bz = b
    dx, dz = bx - ax, bz - az
    length = dx * dx + dz * dz
    if length < 1e-9:
        return math.hypot(point[0] - ax, point[1] - az)

    t = ((point[0] - ax) * dx + (point[1] - az) * dz) / length
    t = min(max(t, 0.0), 1.0)
    return math.hypot(point[0] - (ax + dx * t), point[1] - (az + dz * t))


def camera_corridor():
    """Where the camera goes, as a chain of ground-plane points.

    **A scattered forest will put a tree where the camera stands**, and the
    establishing shot came back as one enormous out-of-focus green facet
    because of it. The camera is nine metres out and the tree rings start at
    five, so this was not bad luck -- it was certain.

    Trees are rejected against this rather than the camera being moved to
    wherever the trees happen not to be, because the shots are the composition
    and the forest is scenery. The scenery gives way.
    """
    path = []
    for _, target, distance, yaw, pitch in SHOTS:
        position, _ = look_at(target, distance, yaw, pitch)
        path.append((position[0], position[2]))
    return path


def look_at(target, distance, yaw, pitch):
    """Where the camera stands to hold `target` in the middle of frame.

    Zero rotation looks down -Z, so forward is
    (-sin yaw cos pitch, sin pitch, -cos yaw cos pitch), and the position is
    the target walked back along it.
    """
    yaw, pitch = math.radians(yaw), math.radians(pitch)
    forward = (-math.sin(yaw) * math.cos(pitch),
               math.sin(pitch),
               -math.cos(yaw) * math.cos(pitch))
    return (tuple(target[i] - forward[i] * distance for i in range(3)),
            (pitch, yaw, 0.0))


# --- the scene ----------------------------------------------------------------

def build(profiles, profile_paths, mat, prop, tex, curve):
    s = Scene()

    # --- the camera and its shots --------------------------------------------
    start, start_rotation = look_at(*SHOTS[0][1:])
    profile = profiles[focus_band(SHOTS[0][2])]

    s.entity("Camp Camera", position=start, rotation=start_rotation)
    s.block("CameraComponent", [
        ("ViewRank", 0), ("FixedAspectRatio", "false"),
        ("ProjectionType", "Perspective"), ("PerspectiveFOV", 50),
        ("PerspectiveNearClip", 0.05), ("PerspectiveFarClip", 400),
        ("OrthographicScale", 10), ("OrthographicNearClip", -1),
        ("OrthographicFarClip", 1),
        ("PostProfile", profile),
    ])
    # Slow. A travel of under four seconds reads as a whip-pan between
    # postcards; at eleven it reads as a camera being carried, and the
    # scene has time to be looked at rather than swept past.
    # **Back to the defaults.** The pacing was slowed three times on request
    # and each step was applied to the already-slowed value rather than to the
    # original, so it compounded: 4.2 s of travel became 11.4, then 24, then
    # 12.7, and every one of those was still slower than the shot before it.
    # 3.4 and 4.2 are what the camera was written with.
    #
    # The focus table rides on the script rather than on twelve markers: one
    # profile *path* per shot, in shot order, comma separated. Written from the
    # same `focus_band` call the profiles themselves were built from, so a band
    # cannot be renumbered here and left stale there.
    #
    # **A path and not a handle, which is not a detail.** The scripting bridge
    # takes an asset field as text and resolves it with Registry::GetHandle,
    # which looks a *path* up -- a handle is the engine's internal name and a
    # script holding one could do nothing honest with it, so the getter hands
    # out paths too. Handing it a handle fails the lookup, SetComponentField
    # returns false, and the camera keeps whatever lens it started with: every
    # shot focused at the first shot's distance, silently, because a refused
    # write reports nothing to the scene.
    shot_profiles = ",".join(profile_paths[focus_band(shot[2])] for shot in SHOTS)
    s.managed_script("CampCamera", HoldSeconds=3.4, TravelSeconds=4.2,
                     Profiles=shot_profiles)

    # The shots themselves. Empty transforms, named so the script can find
    # them -- which makes the camera move a thing you can drag in the editor
    # instead of a table of numbers inside a `.cs`.
    for name, target, distance, yaw, pitch in SHOTS:
        position, rotation = look_at(target, distance, yaw, pitch)

        # **A shot is only a shot if the camera can stand there.** Solving from
        # a target and an angle is the right way to choose a framing and the
        # wrong way to notice that the answer is inside the tent -- shot 4 came
        # out standing in the fire the first time, and the sign of its yaw was
        # the only thing wrong with it. So the three things it can be inside
        # are checked here rather than found in a render.
        floor = ground_height(position[0], position[2])
        if position[1] < floor + 0.35:
            raise SystemExit(
                f"{name} is {floor + 0.35 - position[1]:.2f} m below the "
                f"ground at ({position[0]:.1f}, {position[2]:.1f})")

        # The fire is in this list for the same reason the tent is: it is a
        # solid object at the origin with a ring of stones round it, and a
        # camera inside it sees the inside of a flame.
        for what, at, radius in (("the tent", (3.05, -2.5), 2.2),
                                 ("the van", VAN_AT, 3.4),
                                 # The ring is 0.94 m out and its stones are
                                 # 0.2 m across, so 1.2 m is where the fire
                                 # physically ends. Anything larger than that
                                 # is not a collision, it is an opinion about
                                 # framing -- and it rejected the mirror
                                 # close-up, which is a good shot standing just
                                 # outside the stones.
                                 ("the fire", (0.0, 0.0), 1.2)):
            gap = math.hypot(position[0] - at[0], position[2] - at[1])
            if gap < radius:
                raise SystemExit(
                    f"{name} stands {gap:.2f} m from {what}, which is inside "
                    f"it -- move the target or flip the yaw")

        # A transform and a name, and nothing else. Where the camera stands
        # and what it looks at is all a marker is; its lens is in the table on
        # the script above.
        s.entity(name, position=position, rotation=rotation)

    # --- the ground ----------------------------------------------------------
    s.entity("Ground", position=(0, TERRAIN_Y, 0))
    s.block("TerrainComponent", [
        ("Terrain", tex["terrain"]),
        ("Size", TERRAIN_SIZE), ("Height", TERRAIN_HEIGHT),
        ("Material", mat["ground"]), ("Layer1", mat["scrub"]),
        ("Layer2", 0), ("Layer3", 0),
        ("TextureScale", 26), ("Collision", "true"),
    ])

    # --- the fire ------------------------------------------------------------
    #
    # The centre of the composition and the only real light in the scene, so
    # everything else is placed by where its light falls.

    s.entity("Fire")

    # The ring. Pale stones, and the one thing near the fire that is not warm
    # coloured -- which is what makes it read as a ring rather than as more
    # firelight.
    for i, (x, z, spin, size) in enumerate(scatter(11, 11, 0.82, 0.94)):
        s.entity(f"Ring Stone {i}", parent="Fire",
                 position=(x, ground_height(x, z) - 0.04, z),
                 rotation=(0, spin, 0),
                 scale=(0.62 * size, 0.42 * size, 0.62 * size))
        s.mesh(prop["rock"], mat["stone"])

    s.entity("Fire Logs", parent="Fire", position=(0, 0, 0))
    s.mesh(prop["fire_logs"], mat["charred"])

    # The flame is **modelled**, not simulated. A particle system alone gives a
    # soft orange smudge; the reference's fire is hard-edged, and belonging to
    # the same drawing as the trees matters more here than being convincing on
    # its own.
    s.entity("Flame", parent="Fire", position=(0, 0.16, 0))
    s.mesh(prop["flame_outer"], mat["flame_hot"])

    s.entity("Flame Core", parent="Flame", position=(0, 0.02, 0))
    s.mesh(prop["flame_inner"], mat["flame_core"])

    # Embers rising off it. This is what particles are actually good at, and
    # all that is left for them to do now the flame has a shape.
    s.entity("Embers", parent="Fire", position=(0, 0.55, 0))
    s.block("ParticleEmitterComponent", [
        # An ember off a camp fire floats rather than launches -- it is a scrap
        # of ash with more drag than weight -- and the drag and the long
        # lifetime are what make its rise decelerate. **The speed itself is
        # back where it started**: dropping it to a third as well left the
        # embers barely leaving the flame.
        ("Emit", "true"), ("Rate", 13), ("Burst", 0), ("Lifetime", 2.8),
        ("LifetimeJitter", 0.45), ("Direction", "[0, 1, 0]"), ("Spread", 28),
        ("Speed", 1.15), ("SpeedJitter", 0.6), ("Gravity", "[0.07, 0.42, 0]"),
        ("Drag", 1.2), ("SizeStart", 0.055), ("SizeEnd", 0.012),
        ("ColorStart", "[1, 0.82, 0.4, 1]"), ("ColorEnd", "[1, 0.26, 0.05, 0]"),
        ("Spin", 0.4), ("Facing", "Billboard"), ("Blend", "Additive"),
        ("Space", "World"), ("Texture", tex["spark"]), ("MaxParticles", 220),
        ("SimulateOnGpu", "false"),
        ("SizeCurve", curve["size"]), ("ColorGradient", curve["ember"]),
        ("AlphaCurve", curve["alpha"]),
    ])

    # The heat above it: a few big soft billboards, which is what carries the
    # glow the modelled shards cannot.
    s.entity("Fire Glow", parent="Fire", position=(0, 0.42, 0))
    s.block("ParticleEmitterComponent", [
        ("Emit", "true"), ("Rate", 11), ("Burst", 0), ("Lifetime", 1.2),
        ("LifetimeJitter", 0.3), ("Direction", "[0, 1, 0]"), ("Spread", 22),
        ("Speed", 0.7), ("SpeedJitter", 0.3), ("Gravity", "[0, 0.28, 0]"),
        ("Drag", 2.0), ("SizeStart", 0.5), ("SizeEnd", 0.1),
        ("ColorStart", "[1, 0.6, 0.2, 1]"), ("ColorEnd", "[0.8, 0.2, 0.03, 0]"),
        ("Spin", 0.5), ("Facing", "Billboard"), ("Blend", "Additive"),
        ("Space", "Local"), ("Texture", tex["flame"]), ("MaxParticles", 96),
        ("SimulateOnGpu", "false"),
        ("SizeCurve", curve["size"]), ("ColorGradient", curve["ember"]),
        ("AlphaCurve", curve["alpha"]),
    ])

    # And the smoke, which is the one thing here that has to be *alpha*
    # blended rather than additive. Smoke does not emit light -- it takes it
    # away, and an additive smoke plume is a column of fog lit from inside.
    #
    # World space, so a puff stays where it was born and the column leans away
    # from the fire instead of riding it. Slow, large, and long-lived: a
    # particle that grows from 30 cm to a metre and a half over four seconds is
    # what makes a fire look like it is burning wood rather than gas.
    s.entity("Smoke", parent="Fire", position=(0, 0.95, 0))
    s.block("ParticleEmitterComponent", [
        # **Faint.** The first pass put a pale column up the middle of four of
        # the five shots, brighter in places than the fire it came off -- which
        # inverts the whole composition, because the brightest thing in frame
        # is supposed to be the fire and nothing else. Smoke at night is
        # something you notice second.
        ("Emit", "true"), ("Rate", 4), ("Burst", 0), ("Lifetime", 5.5),
        ("LifetimeJitter", 0.4), ("Direction", "[0, 1, 0]"), ("Spread", 16),
        # Restored with the embers and the glow, and slower than both -- smoke
        # that leaves a fire faster than the sparks in it is smoke off a
        # different fire.
        ("Speed", 0.5), ("SpeedJitter", 0.3), ("Gravity", "[0.12, 0.2, 0.04]"),
        ("Drag", 0.55), ("SizeStart", 0.3), ("SizeEnd", 1.3),
        ("ColorStart", "[0.15, 0.14, 0.16, 0.12]"),
        ("ColorEnd", "[0.08, 0.08, 0.11, 0]"),
        ("Spin", 0.22), ("Facing", "Billboard"), ("Blend", "Alpha"),
        ("Space", "World"), ("Texture", tex["flame"]), ("MaxParticles", 72),
        ("SimulateOnGpu", "false"),
        ("SizeCurve", 0), ("ColorGradient", 0), ("AlphaCurve", curve["alpha"]),
    ])

    # **The range is the composition.** At nine metres the pool of light ends
    # at the chairs and the treeline stays dark, which is the picture. At
    # eighteen it reached the trees and there was no falloff anywhere in frame.
    s.entity("Fire Light", parent="Fire", position=(0, 0.5, 0))
    s.block("LightComponent", [
        ("Type", "Point"), ("Color", "[1, 0.56, 0.24]"), ("Intensity", 9),
        ("Range", 9), ("InnerCone", 20), ("OuterCone", 30),
    ])
    s.block("AudioSourceComponent", [
        # "SFX", not "Sfx". The bus is an enum read by name and a near miss is
        # not a match -- it falls back to Master, silently, and the mixer's
        # SFX slider then does nothing to the fire.
        ("Clip", tex["fire_sound"]), ("Bus", "SFX"), ("Volume", 0.5),
        ("Pitch", 1), ("Loop", "true"), ("PlayOnAwake", "true"),
        ("Stream", "false"), ("Spatial", "true"), ("MinDistance", 2.2),
        ("MaxDistance", 26),
    ])
    # The flicker, which is what stops the firelight reading as a lamp.
    s.managed_script("Flicker", Amount=0.17, Rate=8.5, Base=9.0)

    # The wood that is not on the fire: a stack a metre away, and a few billets
    # that did not make it.
    s.entity("Firewood", position=(1.62, ground_height(1.62, -1.32), -1.32),
             rotation=(0, 0.52, 0))
    s.mesh(prop["firewood"], mat["wood"])

    for i, (x, z, yaw) in enumerate(((1.18, 0.62, 0.9), (-0.98, -0.86, 2.3),
                                     (0.42, 1.28, -0.6))):
        s.entity(f"Billet {i}", position=(x, ground_height(x, z), z),
                 rotation=(0, yaw, 0))
        s.mesh(prop["log_split"], mat["wood"])

    # --- the tent ------------------------------------------------------------
    #
    # Off to one side with its doorway toward the fire, which is where anybody
    # would pitch it and also what keeps the dark opening facing the camera on
    # two of the five shots.
    tent_at = (3.05, -2.5)
    s.entity("Tent", position=(tent_at[0], ground_height(*tent_at), tent_at[1]),
             rotation=(0, math.radians(-52.0), 0))
    s.mesh(prop["tent"], mat["canvas_red"])

    s.entity("Tent Band", parent="Tent")
    s.mesh(prop["tent_band"], mat["canvas_pale"])

    s.entity("Tent Door", parent="Tent")
    s.mesh(prop["tent_door"], mat["shadow"])

    for i, (z, yaw) in enumerate(((1.5, 0.0), (-1.5, math.pi))):
        s.entity(f"Guy Line {i}", parent="Tent", position=(0, 0, z),
                 rotation=(0, yaw, 0))
        s.mesh(prop["guy_line"], mat["rope"])

    # --- the van -------------------------------------------------------------
    #
    # Parked at the edge of the clearing, nose out, and it is the largest thing
    # in the camp by some way. That is what it is for: the scene had nothing
    # between a two-metre tent and a nine-metre tree, and a vehicle is what
    # gives a clearing a reason to be a place somebody arrived at rather than a
    # place that simply exists. It also closes the left of the establishing
    # frame, which had nothing but trees in it.
    s.entity("Van", position=(VAN_AT[0], ground_height(*VAN_AT), VAN_AT[1]),
             rotation=(0, math.radians(104.0), 0))
    s.mesh(prop["van_body"], mat["paint"])

    s.entity("Van Glass", parent="Van")
    s.mesh(prop["van_glass"], mat["glass_dark"])

    s.entity("Van Wheels", parent="Van")
    s.mesh(prop["van_wheels"], mat["rubber"])

    # --- the mirror ----------------------------------------------------------
    #
    # **The one prop where this engine's three reflection paths are visibly
    # different from each other**, which is why it is here at all: the probe
    # gives it the trees and the sky, screen-space reflections give it what is
    # on screen a frame late, and the traced form gives it what is *behind the
    # camera* as well. A scene with nothing polished in it has nothing to say
    # about any of them.
    #
    # On its own kickstand rather than flat against the tent, and turned toward
    # the fire -- which is the whole difference between reflecting a canvas
    # wall and reflecting the thing the scene is about.
    mirror_at = (-2.62, 0.34)
    s.entity("Mirror",
             position=(mirror_at[0], ground_height(*mirror_at), mirror_at[1]),
             rotation=(0, math.radians(102.0), 0))
    s.mesh(prop["mirror_frame"], mat["wood"])

    s.entity("Mirror Glass", parent="Mirror", position=(0, 0, 0.03))
    s.mesh(prop["mirror_glass"], mat["mirror"])

    # Its own probe, at the glass rather than at the camp's centre. A probe
    # captures from a point, and a mirror reflecting a cubemap taken three
    # metres away shows a place it is not standing in.
    s.entity("Mirror Probe", parent="Mirror", position=(0, 0.72, 0.12))
    s.block("ReflectionProbeComponent", [
        ("Update", "Realtime"), ("Resolution", 128), ("Influence", 9),
        ("NearClip", 0.05), ("FarClip", 90), ("Rate", "15Hz"),
        ("FacesPerFrame", 1),
    ])

    # --- what people sit on --------------------------------------------------

    chairs = (
        ("Chair Right", (2.05, 0.95), -116.6, "fabric_blue"),
        ("Chair Back", (2.45, -0.55), -76.6, "fabric_red"),
        # The one in the foreground, facing away from the camera and into the
        # fire. The reference has it and it is doing real work: a shape the eye
        # reads as "somebody sits here" between the lens and the subject.
        ("Chair Near", (-0.62, 2.35), 165.0, "fabric_blue"),
    )
    for name, (x, z), yaw, cloth in chairs:
        s.entity(name, position=(x, ground_height(x, z), z),
                 rotation=(0, math.radians(yaw), 0))
        s.mesh(prop["chair_frame"], mat["metal"])

        s.entity(f"{name} Seat", parent=name)
        s.mesh(prop["chair_seat"], mat[cloth])

    s.entity("Bench Log", position=(-2.3, ground_height(-2.3, -0.5) - 0.02, -0.5),
             rotation=(0, math.radians(28.0), 0))
    s.mesh(prop["log"], mat["wood"])

    s.entity("Stump", position=(1.38, ground_height(1.38, 1.98), 1.98),
             rotation=(0, 0.85, 0))
    s.mesh(prop["stump"], mat["wood"])

    s.entity("Mug", position=(1.38, ground_height(1.38, 1.98) + 0.45, 1.98),
             rotation=(0, 2.2, 0))
    s.mesh(prop["mug"], mat["enamel"])

    # --- the kit -------------------------------------------------------------

    kit = (
        ("Suitcase", "suitcase", (-1.28, -1.58), 0.34, "leather", 0.0),
        ("Bedroll", "bedroll", (-1.28, -1.58), 0.34, "fabric_red", 0.40),
        ("Pack", "pack", (-1.98, -0.38), 0.72, "fabric_dark", 0.0),
        ("Cooler", "cooler", (-2.58, -1.96), -0.26, "plastic", 0.0),
        ("Lantern", "lantern", (-2.58, -1.96), -0.26, "metal", 0.36),
        ("Pot", "pot", (0.98, 0.88), 0.4, "metal", 0.0),
    )
    for name, mesh, (x, z), yaw, surface, lift in kit:
        s.entity(name, position=(x, ground_height(x, z) + lift, z),
                 rotation=(0, yaw, 0))
        s.mesh(prop[mesh], mat[surface])

    s.entity("Lantern Glass", parent="Lantern")
    s.mesh(prop["lantern_glass"], mat["glass_warm"])

    # A second, much smaller pool of light. Two sources at very different
    # strengths is what stops a night scene reading as a single spotlight in a
    # void, and it costs one point light with a three metre reach.
    s.entity("Lantern Light", parent="Lantern", position=(0, 0.15, 0))
    s.block("LightComponent", [
        ("Type", "Point"), ("Color", "[1, 0.82, 0.5]"), ("Intensity", 1.1),
        ("Range", 3.2), ("InnerCone", 20), ("OuterCone", 30),
    ])

    # Toasting forks, reaching into the fire. Leading lines, and the detail
    # that says somebody is sitting here rather than that somebody left.
    for i, (x, z, yaw) in enumerate(((-1.18, 1.02, 130.8), (-0.88, 1.32, 138.0))):
        s.entity(f"Fork {i}", position=(x, ground_height(x, z) + 0.30, z),
                 rotation=(math.radians(6.0), math.radians(yaw), 0))
        s.mesh(prop["fork"], mat["metal"])

        s.entity(f"Marshmallow {i}", parent=f"Fork {i}", position=(0, 0.05, 0.78))
        s.mesh(prop["marshmallow"], mat["white"])

    # --- who is here ---------------------------------------------------------
    #
    # The fox at the edge of the firelight, turned in. The only thing in the
    # scene that is alive, and the whole of the skinning story.
    s.entity("Fox", position=(4.15, ground_height(4.15, 1.95), 1.95),
             rotation=(0, math.radians(-148), 0), scale=(0.009, 0.009, 0.009))
    s.mesh(MESH_FOX, MAT_FOX)
    s.block("AnimatorComponent", [
        # **1.0 -- the clip at the rate it was authored at.** Slowing it read
        # as "calm" in a still and as "stuck" in motion, and the same
        # compounding that got the camera got this: 0.55, then 0.28, then
        # 0.14, each a fraction of the last.
        ("Clip", 0), ("Playing", "true"), ("Loop", "true"), ("Speed", 1.0),
        ("BlendTime", 0.4),
    ])

    # And the name tag over its head. The engine's UI is screen space -- a
    # canvas has a scale mode and no world mode -- so a label belonging to
    # something *in* the scene has to be geometry: a quad wearing a plaque
    # texture, turned to face the camera by `Billboard`. It is lit by the fire,
    # occluded by the tent and reflected in the mirror like anything else,
    # which a screen-space label would not be.
    #
    # The height is the fox's own: about 0.9 m at this scale, and the tag sits
    # a little clear of the ears rather than on them.
    s.entity("Foxy Label",
             position=(4.15, ground_height(4.15, 1.95) + 0.98, 1.95),
             # 42 cm across, which is a third smaller than it first was. A tag
             # wider than the animal it names stops being a label and becomes
             # a sign the animal is standing next to.
             scale=(0.42, 0.158, 1.0))
    s.mesh(QUAD, mat["nameplate"])
    s.managed_script("Billboard")

    # And the rabbits, which are what make the camp feel visited rather than
    # staged. Three, all facing the fire, at the distance an animal actually
    # stops at.
    for i, (x, z, yaw) in enumerate(((1.62, 1.08, -2.15), (2.02, 1.42, -2.42),
                                     (1.26, 1.62, -1.75))):
        s.entity(f"Rabbit {i}", position=(x, ground_height(x, z), z),
                 rotation=(0, yaw, 0))
        s.mesh(prop["rabbit"], mat["fur"])

    # --- the forest ----------------------------------------------------------
    #
    # Rings of pines around the clearing, sparser as they go out so the
    # treeline has depth rather than being a fence. Four tree shapes rather
    # than one at three sizes -- a forest of one silhouette reads as a texture.
    #
    # Canopy and trunk are separate entities because one FBX carries one
    # material, and a green trunk is the detail that gives a low-poly tree away.
    s.entity("Forest")

    corridor = camera_corridor()

    def clear_of_camera(x, z, margin):
        """True if a tree here is out of the camera's way -- and the van's.

        `margin` is the tree's **own canopy radius** plus clearance, not a
        tuned constant. A fixed margin cannot be right for a prop that ships in
        four shapes and is then scaled between 0.78 and 1.33: the number that
        clears a 1.05 m sapling puts the lens inside a 2.6 m pine, which is
        what the camera was flying through.
        """
        # The van is 4.5 m long and sits at a fixed spot, so it gets the same
        # treatment as the camera: the scenery gives way to the things that
        # were placed on purpose.
        if math.hypot(x - VAN_AT[0], z - VAN_AT[1]) < 3.8:
            return False

        for i, point in enumerate(corridor):
            if math.hypot(x - point[0], z - point[1]) < margin:
                return False
            if i + 1 < len(corridor):
                # The travel between two shots as well as the shots
                # themselves -- a tree the camera flies through is worse than
                # one it merely ends up inside, because it flashes.
                # **The full margin, not three quarters of it.** A tree the
                # camera flies through is worse than one it merely ends up
                # inside, because it flashes -- so allowing the travel nearer
                # than the shot is exactly backwards.
                if segment_distance((x, z), point, corridor[i + 1]) < margin:
                    return False
        return True

    def plant(label, kind, x, z, spin, size, surface, trunk_scale=1.0):
        y = ground_height(x, z)
        s.entity(label, parent="Forest", position=(x, y, z),
                 rotation=(0, spin, 0), scale=(size, size * 1.04, size))
        s.mesh(prop[kind], mat[surface])

        s.entity(label + " Trunk", parent=label,
                 scale=(trunk_scale, trunk_scale, trunk_scale))
        s.mesh(prop["pine_trunk"], mat["bark"])

    shapes = ("pine", "pine_tall", "pine_wide", "pine")

    # Each shape's widest tier, from the model. The camera needs to clear this
    # plus its near clip and a little more, or it ends up looking at the inside
    # of a facet.
    canopy = {"pine": 1.55, "pine_tall": 1.35, "pine_wide": 1.95,
              "pine_small": 1.05}
    # The canopy radius is the widest tier's, and a camera passing a tree has a
    # near clip plane and a frame of its own. Two metres on top is what keeps a
    # skirt out of the corner of shot.
    CLEARANCE = 2.2

    for i, (x, z, spin, size) in enumerate(scatter(3, 58, 9.0, 26.0)):
        kind = shapes[i % len(shapes)]
        if not clear_of_camera(x, z, canopy[kind] * size + CLEARANCE):
            continue
        plant(f"Pine {i}", kind, x, z, spin, size, "needle_far",
              trunk_scale=1.15)

    for i, (x, z, spin, size) in enumerate(scatter(7, 38, 6.4, 15.0)):
        kind = shapes[(i + 2) % len(shapes)]
        if not clear_of_camera(x, z, canopy[kind] * size * 0.9 + CLEARANCE):
            continue
        plant(f"Pine Near {i}", kind, x, z, spin, size * 0.9, "needle")

    for i, (x, z, spin, size) in enumerate(scatter(13, 34, 4.8, 12.0)):
        if not clear_of_camera(x, z, canopy["pine_small"] * size + CLEARANCE):
            continue
        plant(f"Sapling {i}", "pine_small", x, z, spin, size, "needle",
              trunk_scale=0.8)

    # The frame's own edges. Five big trees placed by hand rather than
    # scattered, because framing is a decision about the *picture* and a random
    # ring will not make it -- these are the ones the establishing shot looks
    # past, nearer and darker than everything behind them.
    for i, (x, z, size) in enumerate(((-9.6, 8.8, 1.4), (10.6, 7.6, 1.3),
                                      (-9.6, 1.1, 1.15), (9.4, -4.2, 1.2),
                                      (-4.0, 11.6, 1.3))):
        kind = "pine_tall" if i % 2 else "pine"
        if not clear_of_camera(x, z, canopy[kind] * size + CLEARANCE):
            raise SystemExit(
                f"Frame Pine {i} at ({x}, {z}) is in the camera's way. These "
                "five are placed by hand for the composition, so this is a "
                "decision to revisit rather than a tree to drop.")
        plant(f"Frame Pine {i}", kind, x, z, i * 1.7, size, "needle",
              trunk_scale=1.2)

    # --- the ground cover ----------------------------------------------------
    #
    # Tufts and stones, scattered thickly. **These are not decoration.** In the
    # reference they are most of why the ground reads as somewhere rather than
    # as a floor -- there are a great many of them, they are small, and the
    # grass is the brightest colour in the frame after the fire.
    s.entity("Scatter")

    tufts = (("grass", 29, 190), ("grass_tall", 31, 130), ("grass_low", 37, 150))
    for kind, seed, count in tufts:
        for i, (x, z, spin, size) in enumerate(scatter(seed, count, 1.15, 15.0)):
            s.entity(f"Tuft {kind} {i}", parent="Scatter",
                     position=(x, ground_height(x, z) - 0.02, z),
                     rotation=(0, spin, 0),
                     # Half size. At full size a tuft stood higher than the
                     # stump next to it -- in the reference they come about a
                     # third of the way up a chair leg, and they are the
                     # brightest thing in the frame after the fire, so getting
                     # them too big costs the fire its focus as well.
                     scale=(size * 0.5, size * 0.55, size * 0.5))
            s.mesh(prop[kind], mat["blade"])

    for i, (x, z, spin, size) in enumerate(scatter(41, 210, 0.95, 13.0)):
        s.entity(f"Pebble {i}", parent="Scatter",
                 position=(x, ground_height(x, z) - 0.02, z),
                 rotation=(0, spin, 0), scale=(size, size * 0.8, size))
        s.mesh(prop["pebble"], mat["stone_dark"])

    stones = (("rock", 43, 14), ("rock_flat", 47, 12), ("rock_tall", 53, 8))
    for kind, seed, count in stones:
        for i, (x, z, spin, size) in enumerate(scatter(seed, count, 2.6, 15.0)):
            s.entity(f"Stone {kind} {i}", parent="Scatter",
                     position=(x, ground_height(x, z) - 0.06, z),
                     rotation=(0, spin, 0),
                     scale=(size * 0.8, size * 0.7, size * 0.8))
            s.mesh(prop[kind], mat["stone_dark"])

    # --- the night -----------------------------------------------------------
    #
    # One dim directional light standing in for the moon: enough to separate
    # the trees from the sky and give the ground a direction, and nowhere near
    # enough to compete with the fire. A night scene lit only by its fire is a
    # black rectangle with an orange dot in it.
    s.entity("Moon", rotation=(math.radians(-124), math.radians(31), 0))
    s.block("LightComponent", [
        # Its whole job is the *edge* of the trees against the sky.
        ("Type", "Directional"), ("Color", "[0.4, 0.52, 0.85]"),
        ("Intensity", 0.06), ("Range", 60), ("InnerCone", 20),
        ("OuterCone", 30),
    ])

    # The last of the sunset, behind the treeline and low. The reference has a
    # warm glow between the far trunks and it is doing something specific: it
    # separates the dark trees from the dark sky, which the moon alone cannot
    # because it comes from the same side as the camera.
    s.entity("Dusk", rotation=(math.radians(-6), math.radians(196), 0))
    s.block("LightComponent", [
        ("Type", "Directional"), ("Color", "[1, 0.5, 0.28]"),
        ("Intensity", 0.09), ("Range", 80), ("InnerCone", 20),
        ("OuterCone", 30),
    ])

    # Fireflies: world space so they stay where they drift rather than riding
    # the entity, and slow enough to read as insects.
    s.entity("Fireflies", position=(0.5, 1.0, 1.5))
    s.block("ParticleEmitterComponent", [
        ("Emit", "true"), ("Rate", 6), ("Burst", 0), ("Lifetime", 6.0),
        ("LifetimeJitter", 0.5), ("Direction", "[0, 1, 0]"), ("Spread", 180),
        ("Speed", 0.3), ("SpeedJitter", 0.9), ("Gravity", "[0, 0.015, 0]"),
        ("Drag", 0.9), ("SizeStart", 0.045), ("SizeEnd", 0.045),
        ("ColorStart", "[0.8, 1, 0.45, 0]"), ("ColorEnd", "[0.6, 1, 0.3, 0]"),
        ("Spin", 0), ("Facing", "Billboard"), ("Blend", "Additive"),
        ("Space", "World"), ("Texture", tex["spark"]), ("MaxParticles", 56),
        ("SimulateOnGpu", "false"),
        ("SizeCurve", 0), ("ColorGradient", 0), ("AlphaCurve", curve["alpha"]),
    ])

    # A second drift on the far side, so the effect is not one glowing spot.
    s.entity("Fireflies Far", position=(5.4, 1.6, -4.6))
    s.block("ParticleEmitterComponent", [
        ("Emit", "true"), ("Rate", 4), ("Burst", 0), ("Lifetime", 6.5),
        ("LifetimeJitter", 0.5), ("Direction", "[0, 1, 0]"), ("Spread", 180),
        ("Speed", 0.26), ("SpeedJitter", 0.9), ("Gravity", "[0, 0.01, 0]"),
        ("Drag", 0.9), ("SizeStart", 0.04), ("SizeEnd", 0.04),
        ("ColorStart", "[0.75, 1, 0.45, 0]"), ("ColorEnd", "[0.55, 1, 0.3, 0]"),
        ("Spin", 0), ("Facing", "Billboard"), ("Blend", "Additive"),
        ("Space", "World"), ("Texture", tex["spark"]), ("MaxParticles", 40),
        ("SimulateOnGpu", "false"),
        ("SizeCurve", 0), ("ColorGradient", 0), ("AlphaCurve", curve["alpha"]),
    ])

    # --- the screen ----------------------------------------------------------
    #
    # Screen space, and deliberately *not* diegetic: this is the engine talking
    # about itself, so it does not pretend to be part of the clearing. Two
    # things only -- what this is, and the one control a person watching a
    # cinematic actually wants, which is to stop it on a frame they liked.
    #
    # **The canvas origin is the top-left and Y grows downward**, so a band at
    # the bottom of the screen anchors at y = 1 with *negative* offsets. Getting
    # that backwards is what puts a caption along the top.
    s.entity("HUD")
    s.block("UICanvasComponent", [
        ("ScaleMode", "ScaleWithScreen"), ("ReferenceResolution", "[1920, 1080]"),
        ("MatchWidthOrHeight", 0.5), ("SortOrder", 0),
    ])

    def rect(name, parent, anchor_min, anchor_max, offset_min, offset_max,
             order=0, blocks=False):
        s.entity(name, parent=parent)
        s.block("UIRectComponent", [
            ("AnchorMin", vec(*anchor_min)), ("AnchorMax", vec(*anchor_max)),
            ("OffsetMin", vec(*offset_min)), ("OffsetMax", vec(*offset_max)),
            ("SortOrder", order), ("Visible", "true"),
            # Only the button takes the pointer. A backing panel that swallows
            # clicks is the classic UI bug and it is one field.
            ("BlocksPointer", "true" if blocks else "false"),
        ])

    def label(name, parent, text, size, colour, order=1, inset=(0, 0)):
        rect(name, parent, (0, 0), (1, 1), (inset[0], inset[1]),
             (-inset[0], -inset[1]), order)
        s.block("UITextComponent", [
            ("Text", text), ("Font", tex["font"]), ("Size", size),
            ("Color", colour), ("Align", "Center"), ("Wrap", "false"),
            ("LineSpacing", 1),
        ])

    # The caption: small, low contrast, bottom centre. It is a label on a
    # demo, not a title -- anything larger competes with the thing it is
    # labelling.
    rect("Caption", "HUD", (0, 1), (1, 1), (0, -76), (0, -34))
    label("Caption Text", "Caption", "demo camp scene", 22,
          "[0.72, 0.66, 0.6, 0.85]")

    # And the one control. Red on near-black, which is the house accent and
    # the one cool thing in a warm frame, so it stays legible over any part of
    # it.
    #
    # The button *names a method on another entity* rather than carrying a
    # script of its own -- `OnClickTarget` plus `OnClickMethod` -- because the
    # thing being paused is the camera, and the camera is where the state
    # lives. A button with its own copy of "am I paused" is a second source of
    # truth for one bool.
    rect("Pause Button", "HUD", (0.5, 1), (0.5, 1), (-96, -150), (96, -90),
         order=1, blocks=True)
    s.block("UIImageComponent", [("Texture", 0), ("Color", "[0.16, 0.06, 0.07, 0.85]")])
    s.block("UIButtonComponent", [
        ("Interactable", "true"), ("NormalColor", "[0.78, 0.78, 0.8, 1]"),
        ("HoverColor", "[1, 1, 1, 1]"), ("PressedColor", "[0.45, 0.45, 0.5, 1]"),
        ("OnClickTarget", handle_for("Camp Camera")),
        ("OnClickMethod", "TogglePause"),
    ])
    label("Pause Label", "Pause Button", "pause", 24, "[0.92, 0.35, 0.36, 1]",
          order=2, inset=(10, 10))

    # --- what it sounds like -------------------------------------------------
    #
    # A wind bed with crickets in it, seamless by construction and generated by
    # `make_ambience.py`. **Not spatial**: an ambience has no position, and
    # giving it one means the wood goes quiet when the camera walks away from a
    # point in the middle of it. The fire is the spatial one, and the contrast
    # between the two is the point -- the fire arrives as you approach it, and
    # the wood is simply always there.
    s.entity("Night Ambience", position=(0, 2.0, 0))
    s.block("AudioSourceComponent", [
        ("Clip", tex["ambience"]), ("Bus", "SFX"), ("Volume", 0.11),
        ("Pitch", 1), ("Loop", "true"), ("PlayOnAwake", "true"),
        ("Stream", "false"), ("Spatial", "false"), ("MinDistance", 1),
        ("MaxDistance", 200),
    ])

    return s.text()


# --- the assets this scene authors --------------------------------------------

def write_curve(path, channels, keys):
    """A `.rcurve` and its sidecar.

    The camp's flame has a shape of its own: it swells fast, holds, and thins
    out. The courtyard's curves describe a brazier, and borrowing them would be
    the same recycling this scene is not doing anywhere else.
    """
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [f"Curve: {channels}", "Keys:"]
    for time, values in keys:
        lines.append(f"  - T: {time:g}")
        lines.append("    V: [" + ", ".join(f"{v:g}" for v in values) + "]")
    path.write_text(chr(10).join(lines) + chr(10), encoding="utf-8")

    handle = postprofile.profile_handle(path.name)
    path.with_name(path.name + ".meta").write_text(
        f"Handle: {handle}\nType: Curve\n"
        f"SourceHash: {postprofile.source_hash(path)}\n", encoding="utf-8")
    return handle


def materials(tex):
    """Every surface the camp wears, over the camp's own maps.

    **Tiling is a property of the surface, not of the texture.** The props
    carry planar UVs scaled at export, so one tile here is roughly one prop --
    which is what a flat-patch map wants, since the point of it is that a
    handful of facets fall across the object rather than a thousand.
    """
    directory = ASSETS / "materials"

    def surface(name, colour, base, **kwargs):
        maps = {"BaseColor": tex[colour]} if colour else {}
        return write_material(directory / f"camp_{name}.rmat", maps,
                              tiling=kwargs.pop("tiling", (1, 1)),
                              base_color=base, **kwargs)

    return {
        # The clearing floor and the scrub on the rises. The terrain's own
        # TextureScale multiplies these, so the tiling here stays at one.
        # Warm soil brown, not the slate it used to be. The fire is the only
        # warm light in the frame, and a ground that is already cold gives it
        # nothing to warm.
        # Warm, and **dark**. Warm because the fire is the only warm light and
        # a cold ground gives it nothing to warm; dark because the firelight
        # has to be visible *as a pool*, and a ground that is already a mid
        # value everywhere has no room for one.
        "ground": surface("ground", "ground", (0.42, 0.31, 0.22, 1),
                          roughness=0.96, height_scale=0.015),
        "scrub": surface("scrub", "ground", (0.40, 0.40, 0.24, 1),
                         roughness=0.96, height_scale=0.01),

        # Two greens for the canopy, and the difference between them is
        # deliberate: the far ring is darker and bluer, which is the only
        # aerial perspective a scene twenty metres deep can have.
        "needle": surface("needle", "needle", (0.11, 0.28, 0.24, 1),
                          roughness=0.94),
        "needle_far": surface("needle_far", "needle", (0.07, 0.19, 0.20, 1),
                              roughness=0.95),
        "bark": surface("bark", "bark", (0.33, 0.22, 0.16, 1), roughness=0.95),
        "wood": surface("wood", "bark", (0.47, 0.33, 0.22, 1), roughness=0.9),
        # What has been in a fire. Nearly black, and it is what makes the flame
        # above it look hot -- a bright log under a bright flame is a bonfire
        # with no contrast in it.
        "charred": surface("charred", "bark", (0.10, 0.08, 0.08, 1),
                           roughness=0.98),

        "stone": surface("stone", "stone", (0.62, 0.60, 0.60, 1), roughness=0.85),
        "stone_dark": surface("stone_dark", "stone", (0.30, 0.31, 0.38, 1),
                              roughness=0.88),
        "blade": surface("blade", "needle", (0.30, 0.68, 0.20, 1), roughness=0.9),

        "canvas_red": surface("canvas", "canvas", (0.76, 0.13, 0.15, 1),
                              roughness=0.86),
        "canvas_pale": surface("canvas_pale", "canvas", (0.94, 0.92, 0.88, 1),
                               roughness=0.86),
        "shadow": surface("shadow", None, (0.02, 0.02, 0.03, 1), roughness=1.0),
        "rope": surface("rope", "fabric", (0.46, 0.41, 0.33, 1), roughness=0.95),

        # **Emissive above one, and that is the point of the field.** A flame
        # has to survive a tone mapper compressing everything near white; a
        # surface that emits exactly white comes out grey, and a grey flame is
        # the single fastest way to make a night scene look wrong.
        # Backed off from 5.5 and 8.0. Close up -- shot 3 is two metres from
        # the fire -- the flame was clipping to a flat yellow shape with no
        # facets left in it, which loses the one thing that made modelling it
        # rather than emitting particles worth doing.
        "flame_hot": surface("flame_hot", None, (1.0, 0.42, 0.08, 1),
                             roughness=1.0, emissive=(3.8, 1.15, 0.22, 1)),
        "flame_core": surface("flame_core", None, (1.0, 0.88, 0.42, 1),
                              roughness=1.0, emissive=(5.4, 3.3, 0.95, 1)),

        "metal": surface("metal", "metal", (0.09, 0.09, 0.11, 1),
                         metallic=0.7, roughness=0.42),
        "fabric_blue": surface("fabric_blue", "fabric", (0.15, 0.20, 0.52, 1),
                               roughness=0.92),
        "fabric_red": surface("fabric_red", "fabric", (0.66, 0.15, 0.16, 1),
                              roughness=0.92),
        "fabric_dark": surface("fabric_dark", "fabric", (0.16, 0.15, 0.19, 1),
                               roughness=0.94),
        "leather": surface("leather", "bark", (0.43, 0.28, 0.16, 1),
                           roughness=0.7),
        "plastic": surface("plastic", "fabric", (0.78, 0.80, 0.83, 1),
                           roughness=0.55),
        "enamel": surface("enamel", "fabric", (0.86, 0.88, 0.9, 1),
                          roughness=0.4),
        "white": surface("white", None, (0.96, 0.93, 0.86, 1), roughness=0.85),

        # The name tag. A modest flat emissive so the sign is readable four
        # metres from the fire without being a lamp -- and the letters stay
        # dark because they are dark in the *map*, which is the only way to
        # have a partly-glowing surface with no emissive map to vary it.
        "nameplate": surface("nameplate", "foxy", (1.0, 1.0, 1.0, 1),
                             roughness=0.85, emissive=(0.34, 0.3, 0.24, 1)),

        # The van. Pale green paint, because the frame already has a red tent
        # in it and a second saturated body colour would fight it for the eye;
        # a muted one reads as a vehicle and stays out of the way.
        # Dark, not pale. At two-thirds white the van was the brightest large
        # object in a night frame and pulled the eye off the fire, which is the
        # one thing this composition cannot afford.
        # **Light enough to read as a vehicle.** At a third of white the van
        # was a dark grey box in a dark frame and looked like a shipping
        # container -- no windows, no wheels, no roof line, because none of
        # them had any value to differ by. The paint has to be well above the
        # glass and the tyres or the shape has nothing in it.
        #
        # Still muted: the frame already has a red tent for its saturated
        # colour, and a second one would fight it.
        "paint": surface("paint", "metal", (0.54, 0.58, 0.51, 1),
                         metallic=0.35, roughness=0.45),
        "glass_dark": surface("glass_dark", None, (0.05, 0.07, 0.10, 1),
                              metallic=0.2, roughness=0.12),
        "rubber": surface("rubber", "metal", (0.06, 0.06, 0.07, 1),
                          roughness=0.9),
        "fur": surface("fur", "fabric", (0.38, 0.32, 0.29, 1), roughness=0.95),
        "glass_warm": surface("lantern_glass", None, (1.0, 0.9, 0.62, 1),
                              roughness=0.3, emissive=(3.0, 2.1, 0.9, 1)),

        # The glass. Metal at almost zero roughness, which is what a mirror
        # *is* -- silvered glass is a metal surface with a pane in front of it,
        # and modelling the pane separately would buy a refraction this
        # renderer does not do.
        #
        # Not pure white: a real mirror returns about 95 % and a perfect one
        # looks wrong beside surfaces that do not.
        "mirror": surface("mirror", None, (0.95, 0.96, 0.97, 1),
                          metallic=1.0, roughness=0.03),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=str(ASSETS / "scenes" / "camp.rage"))
    args = parser.parse_args()

    prop = handles_in(ASSETS / "models" / "camp", ".fbx", "")
    require(prop, "pine", "pine_tall", "pine_wide", "pine_small", "pine_trunk",
            "tent", "tent_band", "tent_door", "guy_line", "flame_outer",
            "flame_inner", "fire_logs", "firewood", "log_split", "chair_frame",
            "chair_seat", "log", "stump", "rock", "rock_flat", "rock_tall",
            "pebble", "grass", "grass_tall", "grass_low", "pack", "bedroll",
            "suitcase", "cooler", "lantern", "lantern_glass", "pot", "mug",
            "fork", "marshmallow", "mirror_frame", "mirror_glass", "rabbit",
            "van_body", "van_glass", "van_wheels")

    tex = handles_in(ASSETS / "materials", "_color.png", "camp_")
    tex.update({
        "flame": read_handle(ASSETS / "textures" / "camp_flame.png.meta"),
        "spark": read_handle(ASSETS / "textures" / "camp_spark.png.meta"),
        "foxy": read_handle(ASSETS / "textures" / "camp_foxy.png.meta"),
        "lut": read_handle(ASSETS / "post" / "camp.rvlut.meta"),
        "terrain": read_handle(ASSETS / "terrain" / "clearing.rvterrain.meta"),
        "fire_sound": read_handle(ASSETS / "audio" / "camp_fire.wav.meta"),
        "ambience": read_handle(ASSETS / "audio" / "camp_night.wav.meta"),
        "font": read_handle(ASSETS / "fonts" / "roboto.rvfont.meta"),
    })
    require(tex, "ground", "bark", "canvas", "fabric", "stone", "needle",
            "metal", "flame", "spark", "lut", "terrain", "fire_sound",
            "ambience", "font", "foxy")

    curves = ASSETS / "curves"
    curve = {
        # A tongue of flame is widest a third of the way up and narrows again
        # as it burns out. Two endpoints can only widen or only narrow, so this
        # is the shape a start/end pair cannot hold.
        "size": write_curve(curves / "camp_flame_size.rcurve", 1,
                            ((0.0, [0.28]), (0.28, [0.9]), (0.62, [0.58]),
                             (1.0, [0.12]))),
        # An ember has no hard edge at either end: it appears out of nothing
        # and thins out rather than being switched off.
        "alpha": write_curve(curves / "camp_flame_alpha.rcurve", 1,
                             ((0.0, [0.0]), (0.1, [1.0]), (0.5, [0.65]),
                              (1.0, [0.0]))),
        # Through orange on the way from yellow to a dark red, which a straight
        # crossfade would cut the corner of -- and cutting that corner is
        # exactly what makes a fire look like a light bulb.
        "ember": write_curve(curves / "camp_ember.rcurve", 3,
                             ((0.0, [1.0, 0.94, 0.6]), (0.3, [1.0, 0.52, 0.14]),
                              (0.72, [0.68, 0.15, 0.04]),
                              (1.0, [0.2, 0.03, 0.02]))),
    }

    mat = materials(tex)

    # Night, and every effect chosen for the picture.
    settings = {
        # **Fixed, not automatic.** Auto exposure hunts for a mid-grey and
        # finds one in any scene, so a night scene comes back correctly exposed
        # and therefore not night. The fire is the subject; it should be the
        # only thing near white in the frame.
        "Exposure": 0.78,
        "AutoExposure": False,

        "BloomEnabled": True,
        # Above the lit ground, so only the flame blooms. Below it, bloom
        # spreads the firelight over the whole clearing and undoes the falloff
        # the light was tuned for.
        "BloomThreshold": 1.45,
        "BloomKnee": 0.4,
        "BloomIntensity": 0.075,
        "BloomClamp": 14.0,

        # **The depth of field is most of why the reference reads as a
        # miniature**, and it is not subtle there: the foreground trees and the
        # treeline are both well out of focus and only the camp is sharp.
        "DepthOfField": True,
        # **One focus distance has to serve twelve shots**, and they range from
        # 2.3 m (the mirror, close) to 9.6 m (the final wide). At 7.2 m and
        # f/1.45 the establishing shot was beautiful and the fox -- the subject
        # of the shot that closes the film -- was a soft orange smear, along
        # with its name tag. Five metres and f/2 keeps the near shots readable
        # and still throws the treeline out on the wides, which is where the
        # miniature effect actually comes from.
        #
        # A focus distance per shot would be better and is not available: the
        # profile is an asset the camera points at, not a field a script can
        # set.
        # Overridden per band below; the value here is the fallback for
        # anything that reads this dict directly.
        "FocusDistance": 5.4,
        "FocalLength": 55.0,
        # Back to a shallow stop now that each shot focuses on its own subject.
        # The shallow depth is most of why the reference reads as a miniature,
        # and it was only stopped down to paper over one focus serving twelve
        # shots.
        "Aperture": 1.8,
        "MaxBokehRadius": 14.0,

        # **Screen-space reflections, and the mirror is what they are for.**
        # Between them the probe, the screen-space pass and the traced pass are
        # three different answers to the same question, and the mirror is the
        # one surface in the scene where you can see them disagree: the probe
        # supplies what a cubemap taken at the glass sees, SSR corrects it with
        # what is actually on screen, and tracing adds what is behind the
        # camera. Turning any of them off is visible in that one rectangle.
        "ScreenSpaceReflections": True,
        "SsrMaxDistance": 26.0,
        "SsrThickness": 0.4,
        "SsrIntensity": 1.0,

        "AmbientOcclusion": True,
        "AoRadius": 0.5,
        "AoIntensity": 0.85,

        "GlobalIllumination": True,
        "GiRadius": 2.5,
        "GiQuality": "Low",
        # **0.4, not 1.1.** With the project's ray-traced GI switched on as
        # well, indirect light at full strength lifts the whole clearing to an
        # even dusk: the ground away from the fire stops being dark, the
        # falloff the fire's range was tuned for disappears, and the scene
        # reads as an overcast afternoon with an orange prop in it. Bounce
        # light is worth having here for the warm spill onto the chairs and the
        # tent, and that is all it is worth having for.
        "GiIntensity": 0.4,
        # One bounce. The fire is the only bright thing here, so a second
        # bounce spends its time carrying almost nothing into the dark.
        "GiBounces": 1,
        "GiDenoise": 0.9,

        # Voxel GI as well, because the fire is a *local* source in a scene
        # with no sky light to speak of -- and the warm bounce off the ground
        # onto the chairs and the tent is a good part of why a campfire reads
        # as one. A screen-space method alone loses it the moment the ground
        # leaves the frame.
        "VoxelGlobalIllumination": True,
        "VoxelGiResolution": 128,
        "VoxelGiCascades": 2,
        "VoxelGiVoxelSize": 0.22,

        "MotionBlur": True,
        "MotionBlurShutter": 0.4,
        # The camera moves slowly and the blur should stay a smear rather than
        # becoming a comet: capped well below the default.
        "MotionBlurMaxRadius": 8.0,

        "ColorLut": tex["lut"],
        "ColorLutStrength": 0.85,

        "VignetteIntensity": 0.44,
        "VignetteSmoothness": 0.7,
        "ChromaticAberration": 0.0011,
        # Low. The reference is a rendered poster, not film -- grain is the one
        # effect that makes a clean low-poly image look like a photograph of a
        # screen. Enough to keep the dark parts from banding and no more.
        "FilmGrain": 0.07,
        "FilmGrainSize": 1.5,
    }

    # One profile per focus band, identical in every other respect. The camp's
    # own `camp.rvpostprofile` stays as the mid band under its old name, so a
    # camera that has not been told otherwise still grades the scene correctly.
    profiles = {}
    profile_paths = {}
    for band in FOCUS_BANDS:
        name = ("camp.rvpostprofile" if band == 5.4
                else "camp_focus_{0}.rvpostprofile".format(
                    str(band).replace(".", "_")))
        profiles[band] = postprofile.write_named(
            ASSETS / "post" / name, dict(settings, FocusDistance=band))
        # What the asset registry will call this file: relative to the asset
        # directory, forward slashes, which is what GetHandle matches on.
        profile_paths[band] = "post/" + name

    scene = build(profiles, profile_paths, mat, prop, tex, curve)

    header = [
        "Scene: Camp",
        # **Without this the loader throws every EntityID away.** A file with
        # no Version is version 1, and version 1 wrote the same hardcoded id
        # for every entity -- so the reader mints fresh ids instead of
        # honouring what is on disk. The entities still load and the scene
        # still renders, and then every single parent reference resolves to
        # nothing: the tent's pale band and its doorway sat on the campfire
        # three metres from the tent, every chair lost its seat, and a hundred
        # tree trunks stacked up on the origin in one brown column.
        f"Version: {SCENE_VERSION}",
        "Environment:",
        "  Ambient: [0.028, 0.03, 0.055]",
        "  AmbientIntensity: 1",
        # **A gradient, not a panorama.** A cubemap sky is the scene's
        # image-based light as well as its backdrop, so a dusk HDR lights every
        # surface in the clearing with dusk -- which is exactly what the trees
        # came back as, and turning the moon down could never have fixed it,
        # because the moon was not what was lighting them.
        #
        # Nearly black, with the last of the sunset left in the horizon band.
        "  Sky: Gradient",
        "  SkyHorizon: [0.10, 0.07, 0.11]",
        "  SkyZenith: [0.014, 0.018, 0.048]",
        "  SkyGround: [0.008, 0.01, 0.018]",
        "  SkyIntensity: 1",
        "  SkyRotation: 0",
        "Entities:",
    ]

    path = pathlib.Path(args.output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(chr(10).join(header) + chr(10) + scene + chr(10),
                    encoding="utf-8")

    entities = scene.count("  - EntityID:")
    print(f"{path}: {entities} entities")
    print(f"  {len(prop)} props, {len(mat)} materials, {len(curve)} curves")
    print(f"  focus     " + ", ".join(
        f"{name}@{focus_band(distance):g}m"
        for name, _, distance, _, _ in SHOTS))
    for name, target, distance, yaw, pitch in SHOTS:
        position, _ = look_at(target, distance, yaw, pitch)
        print(f"  {name}    at ({position[0]:.2f}, {position[1]:.2f}, "
              f"{position[2]:.2f})  looking at {target}")


if __name__ == "__main__":
    main()
