#!/usr/bin/env python3
"""Write `.cube` colour LUTs with known transforms, and their sidecars.

Two of them, and the first is the important one.

**identity** -- every entry is its own coordinate, so grading with it must
change nothing at all. That is the whole check: a 3D LUT is sampled at texel
*centres*, so a colour c maps to `(c * (N-1) + 0.5) / N` and not to `c`, and
getting that half-texel wrong produces a grade that is smooth, plausible, and
not the one that was authored -- everywhere, forever, with no artefact to
point at. Nothing about the picture reveals it. An identity LUT does.
ENGINE-NOTES 7t.

**swap** -- red and blue exchanged. Exact under trilinear interpolation,
because it moves table entries rather than blending them, so the expected
output is known to the bit rather than to a tolerance. It separates "the LUT
is sampled at all" from "the LUT is sampled correctly", which would otherwise
be one failure wearing two faces.

The sidecar is written too, for the reason postprofile.py writes one: a handle
is minted by the registry on first scan, which is after the file naming it has
to exist, so a generator cannot ask for one.

    python tools/scripts/make_lut.py --kind identity \
        --output SampleProject/assets/luts/identity.cube
"""

import argparse
import pathlib

import postprofile


def cinematic(red, green, blue):
    """A split-toned contrast grade, on display-referred values.

    **This runs after the tone curve**, which is where a `.cube` from any
    grading tool expects to be, so what it is shaping is the picture rather
    than the scene. Three things, in the order a colourist would do them:

    - **An S-curve**, gentle. Contrast is what separates a photograph from a
      render more than any single other operation, and a straight multiply
      round the midpoint crushes both ends -- the smoothstep keeps the toe
      and the shoulder rolling.
    - **Split toning**: shadows toward teal, highlights toward warm. It is a
      cliche because it works, and it works because it is what film stock did
      -- the dyes were never neutral at both ends.
    - **A saturation lift**, small, applied last so it acts on the graded
      colour rather than the raw one.
    """
    lum = 0.2126 * red + 0.7152 * green + 0.0722 * blue

    def curve(v):
        # A smoothstep blended against the identity: full smoothstep is far
        # too much contrast, and this keeps the ends alive.
        s_curve = v * v * (3.0 - 2.0 * v)
        return v + (s_curve - v) * 0.45

    red, green, blue = curve(red), curve(green), curve(blue)

    # Shadows cool, highlights warm, weighted by where this value sits.
    t = lum * lum * (3.0 - 2.0 * lum)
    shadow = (0.90, 1.00, 1.10)
    highlight = (1.08, 1.01, 0.92)
    tint = tuple(shadow[i] + (highlight[i] - shadow[i]) * t for i in range(3))
    red, green, blue = red * tint[0], green * tint[1], blue * tint[2]

    graded = 0.2126 * red + 0.7152 * green + 0.0722 * blue
    saturation = 1.14
    red = graded + (red - graded) * saturation
    green = graded + (green - graded) * saturation
    blue = graded + (blue - graded) * saturation

    clamp = lambda v: min(max(v, 0.0), 1.0)
    return clamp(red), clamp(green), clamp(blue)


def build(kind, size):
    """The `.cube` text. Red changes fastest, which is the format's order."""
    lines = [
        f"# Generated by tools/scripts/make_lut.py ({kind})",
        f"LUT_3D_SIZE {size}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
    ]

    step = 1.0 / (size - 1)

    for b in range(size):
        for g in range(size):
            for r in range(size):
                red, green, blue = r * step, g * step, b * step
                if kind == "swap":
                    red, blue = blue, red
                elif kind == "cinematic":
                    red, green, blue = cinematic(red, green, blue)
                lines.append(f"{red:.6f} {green:.6f} {blue:.6f}")

    return "\n".join(lines) + "\n"


def write(path, kind, size=33):
    """Writes the LUT and its `.meta`. Returns the handle a profile names."""
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build(kind, size), encoding="utf-8")

    handle = postprofile.profile_handle(path.name)
    meta = path.with_name(path.name + ".meta")
    meta.write_text(f"Handle: {handle}\nType: ColorLut\nSourceHash: 0\n",
                    encoding="utf-8")

    return handle


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--kind", choices=("identity", "swap", "cinematic"),
                        default="identity")
    # 33 is what grading tools emit most often, and is odd -- so the midpoint
    # of the range lands exactly on a table entry rather than between two,
    # which makes a sampling mistake at the centre visible rather than
    # smoothed over.
    parser.add_argument("--size", type=int, default=33)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    handle = write(args.output, args.kind, args.size)
    print(f"wrote {args.output} ({args.kind}, {args.size}^3, handle {handle})")


if __name__ == "__main__":
    main()
