#!/usr/bin/env python3
"""Write `.cube` colour LUTs with known transforms, and their sidecars.

Two of them, and the first is the important one.

**identity** -- every entry is its own coordinate, so grading with it must
change nothing at all. That is the whole check: a 3D LUT is sampled at texel
*centres*, so a colour c maps to `(c * (N-1) + 0.5) / N` and not to `c`, and
getting that half-texel wrong produces a grade that is smooth, plausible, and
not the one that was authored -- everywhere, forever, with no artefact to
point at. Nothing about the picture reveals it. An identity LUT does.
ENGINE-NOTES 7t.

**swap** -- red and blue exchanged. Exact under trilinear interpolation,
because it moves table entries rather than blending them, so the expected
output is known to the bit rather than to a tolerance. It separates "the LUT
is sampled at all" from "the LUT is sampled correctly", which would otherwise
be one failure wearing two faces.

The sidecar is written too, for the reason postprofile.py writes one: a handle
is minted by the registry on first scan, which is after the file naming it has
to exist, so a generator cannot ask for one.

    python tools/scripts/make_lut.py --kind identity \
        --output SampleProject/assets/luts/identity.cube
"""

import argparse
import pathlib

import postprofile


def build(kind, size):
    """The `.cube` text. Red changes fastest, which is the format's order."""
    lines = [
        f"# Generated by tools/scripts/make_lut.py ({kind})",
        f"LUT_3D_SIZE {size}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
    ]

    step = 1.0 / (size - 1)

    for b in range(size):
        for g in range(size):
            for r in range(size):
                red, green, blue = r * step, g * step, b * step
                if kind == "swap":
                    red, blue = blue, red
                lines.append(f"{red:.6f} {green:.6f} {blue:.6f}")

    return "\n".join(lines) + "\n"


def write(path, kind, size=33):
    """Writes the LUT and its `.meta`. Returns the handle a profile names."""
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build(kind, size), encoding="utf-8")

    handle = postprofile.profile_handle(path.name)
    meta = path.with_name(path.name + ".meta")
    meta.write_text(f"Handle: {handle}\nType: ColorLut\nSourceHash: 0\n",
                    encoding="utf-8")

    return handle


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--kind", choices=("identity", "swap"), default="identity")
    # 33 is what grading tools emit most often, and is odd -- so the midpoint
    # of the range lands exactly on a table entry rather than between two,
    # which makes a sampling mistake at the centre visible rather than
    # smoothed over.
    parser.add_argument("--size", type=int, default=33)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    handle = write(args.output, args.kind, args.size)
    print(f"wrote {args.output} ({args.kind}, {args.size}^3, handle {handle})")


if __name__ == "__main__":
    main()
