#!/usr/bin/env python3
"""Write the same shape as an ASCII FBX and as a glTF, from one description.

The importer needs something to import, and downloading a model makes the
check depend on a file nobody can regenerate -- the argument
make_skinned_gltf.py and make_sky_hdr.py both already make.

**Both formats from one source is the point of this one.** The failure an FBX
importer actually has is a space error: an axis swapped, a handedness flipped,
a unit left in centimetres. None of those is visible in a single file -- the
model looks like *something* and you have no second opinion. Emitting the same
vertices twice, and asserting the two imports agree, turns "is this right" into
a comparison against a known answer.

So the shape is chosen to make a space error impossible to miss:

  * **Not centred on the origin.** A symmetric shape hides sign errors.
  * **Different in all three dimensions** (0.6 x 1.4 x 0.9). A cube hides an
    axis swap completely -- the classic reason an importer ships broken.
  * **One corner cut**, so the shape is chiral: a mirrored import differs from
    a correct one even when the bounding box matches.

The material is a plain Phong, on purpose. It is what an FBX carries natively,
and it is the case the importer makes a promise about: the colour transfers,
metallic and roughness stay at the engine's defaults, and the log says why. The
vendor PBR extras -- Maya's Stingray, Max's Physical Material -- need the shader
graph objects that surround them to be detected at all, which cannot be faked
convincingly by hand; that path is exercised by ufbx's own test suite rather
than by this fixture, and ENGINE-NOTES 7bn says so.

    python tools/scripts/make_fbx_fixture.py

Writes SampleProject/assets/models/spacecheck.fbx and spacecheck.gltf.

ASCII FBX 7.4 rather than binary. It is the format's own text form, ufbx reads
it, and a fixture somebody can open in a text editor and check by eye is worth
more here than a few kilobytes.
"""

import argparse
import base64
import json
import pathlib
import struct
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]


# --- the shape ----------------------------------------------------------------
#
# A box from (0.2, 0.1, -0.3) to (0.8, 1.5, 0.6), with the +X+Y+Z corner pulled
# in so the solid has no mirror symmetry. Written once, emitted twice.
MIN = (0.2, 0.1, -0.3)
MAX = (0.8, 1.5, 0.6)
CUT = (0.55, 1.1, 0.25)     # where the cut corner sits instead of MAX


def corners():
    """The eight corners, with the last one pulled in."""
    x0, y0, z0 = MIN
    x1, y1, z1 = MAX
    return [
        (x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
        (x0, y0, z1), (x1, y0, z1), CUT,          (x0, y1, z1),
    ]


# Each face as four corner indices, wound counter-clockwise seen from outside.
QUADS = [
    (0, 3, 2, 1),   # -Z
    (4, 5, 6, 7),   # +Z
    (0, 1, 5, 4),   # -Y
    (3, 7, 6, 2),   # +Y
    (0, 4, 7, 3),   # -X
    (1, 2, 6, 5),   # +X
]

NORMALS = [
    (0.0, 0.0, -1.0), (0.0, 0.0, 1.0),
    (0.0, -1.0, 0.0), (0.0, 1.0, 0.0),
    (-1.0, 0.0, 0.0), (1.0, 0.0, 0.0),
]


def write_fbx(path):
    """ASCII FBX 7.4 with one mesh in it.

    Deliberately minimal: the sections ufbx needs to find geometry, and no
    more. `PolygonVertexIndex` uses FBX's own convention where the last index
    of a face is stored as its bitwise complement, which is how the format
    marks a face boundary without a separate count.
    """
    points = corners()

    vertices = []
    for point in points:
        vertices.extend(point)

    indices = []
    for quad in QUADS:
        indices.extend(quad[:-1])
        indices.append(~quad[-1])       # the negated terminator

    normals = []
    for face in range(len(QUADS)):
        for _ in range(4):
            normals.extend(NORMALS[face])

    # Bottom-left origin, which is FBX's convention and the reason the importer
    # flips V on the way in.
    uvs = [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]
    uv_indices = list(range(4)) * len(QUADS)

    def numbers(values, per_line=6):
        out, line = [], []
        for value in values:
            line.append('{0:g}'.format(value))
            if len(line) == per_line:
                out.append(','.join(line))
                line = []
        if line:
            out.append(','.join(line))
        return (',\n' + ' ' * 12).join(out)

    text = '''; FBX 7.4.0 project file
; Generated by tools/scripts/make_fbx_fixture.py -- do not edit by hand.
; The same shape is in spacecheck.gltf; check_fbx.py asserts they agree.

FBXHeaderExtension:  {{
    FBXHeaderVersion: 1003
    FBXVersion: 7400
    Creator: "RageV fixture generator"
}}
GlobalSettings:  {{
    Version: 1000
    Properties70:  {{
        P: "UpAxis", "int", "Integer", "",1
        P: "UpAxisSign", "int", "Integer", "",1
        P: "FrontAxis", "int", "Integer", "",2
        P: "FrontAxisSign", "int", "Integer", "",1
        P: "CoordAxis", "int", "Integer", "",0
        P: "CoordAxisSign", "int", "Integer", "",1
        ; Centimetres per unit -- so 100 means one unit is one metre.
        ; Written as 1 first, which made ufbx divide the shape by a
        ; hundred, exactly as it should have: the check caught it and the
        ; importer was right.
        P: "UnitScaleFactor", "double", "Number", "",100
    }}
}}

Definitions:  {{
    Version: 100
    Count: 3
    ObjectType: "Geometry" {{
        Count: 1
    }}
    ObjectType: "Model" {{
        Count: 1
    }}
    ObjectType: "Material" {{
        Count: 1
    }}
}}

Objects:  {{
    Geometry: 1000, "Geometry::SpaceCheck", "Mesh" {{
        Vertices: *{vertex_count} {{
            a: {vertices}
        }}
        PolygonVertexIndex: *{index_count} {{
            a: {indices}
        }}
        GeometryVersion: 124
        LayerElementNormal: 0 {{
            Version: 101
            Name: ""
            MappingInformationType: "ByPolygonVertex"
            ReferenceInformationType: "Direct"
            Normals: *{normal_count} {{
                a: {normals}
            }}
        }}
        LayerElementUV: 0 {{
            Version: 101
            Name: "UVMap"
            MappingInformationType: "ByPolygonVertex"
            ReferenceInformationType: "IndexToDirect"
            UV: *{uv_count} {{
                a: {uvs}
            }}
            UVIndex: *{uv_index_count} {{
                a: {uv_indices}
            }}
        }}
        LayerElementMaterial: 0 {{
            Version: 101
            Name: ""
            MappingInformationType: "AllSame"
            ReferenceInformationType: "IndexToDirect"
            Materials: *1 {{
                a: 0
            }}
        }}
        Layer: 0 {{
            Version: 100
            LayerElement:  {{
                Type: "LayerElementNormal"
                TypedIndex: 0
            }}
            LayerElement:  {{
                Type: "LayerElementUV"
                TypedIndex: 0
            }}
            LayerElement:  {{
                Type: "LayerElementMaterial"
                TypedIndex: 0
            }}
        }}
    }}
    Model: 2000, "Model::SpaceCheck", "Mesh" {{
        Version: 232
        Properties70:  {{
            P: "Lcl Translation", "Lcl Translation", "", "A",0,0,0
            P: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0
            P: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1
        }}
        Shading: T
        Culling: "CullingOff"
    }}
    Material: 3000, "Material::SpaceCheckMaterial", "" {{
        Version: 102
        ShadingModel: "phong"
        MultiLayer: 0
        Properties70:  {{
            P: "DiffuseColor", "Color", "", "A",0.8,0.35,0.2
            P: "SpecularColor", "Color", "", "A",0.2,0.2,0.2
            P: "ShininessExponent", "Number", "", "A",24
        }}
    }}
}}

Connections:  {{
    C: "OO",2000,0
    C: "OO",1000,2000
    C: "OO",3000,2000
}}
'''.format(
        vertex_count=len(vertices), vertices=numbers(vertices),
        index_count=len(indices), indices=numbers(indices, 8),
        normal_count=len(normals), normals=numbers(normals),
        uv_count=len(uvs), uvs=numbers(uvs, 8),
        uv_index_count=len(uv_indices), uv_indices=numbers(uv_indices, 8))

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')
    return len(text)


def write_gltf(path):
    """The same shape as glTF, triangulated, for the comparison to be against."""
    points = corners()

    positions, normals, uvs, indices = [], [], [], []
    for face, quad in enumerate(QUADS):
        base = len(positions)
        for corner, index in enumerate(quad):
            positions.append(points[index])
            normals.append(NORMALS[face])
            uvs.append([(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)][corner])
        indices.extend([base, base + 1, base + 2, base, base + 2, base + 3])

    blob = b''
    offsets = {}
    for name, values, fmt in (('position', positions, '<3f'),
                              ('normal', normals, '<3f'),
                              ('uv', uvs, '<2f')):
        offsets[name] = len(blob)
        for value in values:
            blob += struct.pack(fmt, *value)

    offsets['index'] = len(blob)
    for index in indices:
        blob += struct.pack('<H', index)
    while len(blob) % 4:
        blob += b'\x00'

    def bounds(values, axis):
        return [min(v[axis] for v in values), max(v[axis] for v in values)]

    document = {
        'asset': {'version': '2.0', 'generator': 'RageV make_fbx_fixture.py'},
        'scene': 0,
        'scenes': [{'nodes': [0]}],
        'nodes': [{'name': 'SpaceCheck', 'mesh': 0}],
        'meshes': [{'name': 'SpaceCheck', 'primitives': [{
            'attributes': {'POSITION': 0, 'NORMAL': 1, 'TEXCOORD_0': 2},
            'indices': 3, 'material': 0}]}],
        'materials': [{
            'name': 'SpaceCheckMaterial',
            'pbrMetallicRoughness': {
                'baseColorFactor': [0.8, 0.35, 0.2, 1.0],
                'metallicFactor': 0.1,
                'roughnessFactor': 0.65}}],
        'accessors': [
            {'bufferView': 0, 'componentType': 5126, 'count': len(positions),
             'type': 'VEC3',
             'min': [bounds(positions, i)[0] for i in range(3)],
             'max': [bounds(positions, i)[1] for i in range(3)]},
            {'bufferView': 1, 'componentType': 5126, 'count': len(normals),
             'type': 'VEC3'},
            {'bufferView': 2, 'componentType': 5126, 'count': len(uvs),
             'type': 'VEC2'},
            {'bufferView': 3, 'componentType': 5123, 'count': len(indices),
             'type': 'SCALAR'},
        ],
        'bufferViews': [
            {'buffer': 0, 'byteOffset': offsets['position'],
             'byteLength': len(positions) * 12, 'target': 34962},
            {'buffer': 0, 'byteOffset': offsets['normal'],
             'byteLength': len(normals) * 12, 'target': 34962},
            {'buffer': 0, 'byteOffset': offsets['uv'],
             'byteLength': len(uvs) * 8, 'target': 34962},
            {'buffer': 0, 'byteOffset': offsets['index'],
             'byteLength': len(indices) * 2, 'target': 34963},
        ],
        'buffers': [{
            'byteLength': len(blob),
            'uri': 'data:application/octet-stream;base64,'
                   + base64.b64encode(blob).decode('ascii')}],
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(document, indent=1), encoding='utf-8')
    return len(indices) // 3


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', default=str(ROOT / 'SampleProject' / 'assets' / 'models'))
    args = parser.parse_args()

    directory = pathlib.Path(args.output)
    fbx = directory / 'spacecheck.fbx'
    gltf = directory / 'spacecheck.gltf'

    size = write_fbx(fbx)
    triangles = write_gltf(gltf)

    sys.stdout.write('wrote {0} ({1} bytes)\n'.format(fbx, size))
    sys.stdout.write('wrote {0} ({1} triangles)\n'.format(gltf, triangles))
    sys.stdout.write('the same {0} corners, {1} faces, in both\n'.format(
        len(corners()), len(QUADS)))


if __name__ == '__main__':
    main()
