"""T5 halted at the owner's word (93% of the usage limit) with the design
written and nothing built: the build notes gathered from the code go into
RT-FIRST.md section 2d so the next session starts at the patch, not at the
reading; the hand-off header and memory say where things stand."""
import os
os.chdir(r'C:\Users\ism19\Code\RageV')

def load(p):
    s = open(p, 'rb').read().decode('utf-8'); return s, ('\r\n' if '\r\n' in s else '\n')
def save(p, s):
    open(p, 'wb').write(s.encode('utf-8')); print('ok', p)
def rep(s, nl, old, new, count=1):
    o = old.replace('\n', nl); n = new.replace('\n', nl)
    assert s.count(o) == count, (s.count(o), old[:70]); return s.replace(o, n)

# ---- RT-FIRST.md: the build notes under the T5 design, and the row
p = 'docs/RT-FIRST.md'; s, nl = load(p)
anchor = '## 3 · What this does to the open lists'
notes = """### T5 build notes, gathered 2026-09-06 before the halt (nothing built; start the patch from here)

**State:** the design above is written; no file outside `docs/` was changed for T5. Both builds and both staged shader folders are at the T4 state (verified pixel-identical). Halted at 93% of the usage limit on the owner's word.

**Where the passes go.** Between `graph.AddPass("GBuffer", …)` (FrameGraphBuilder.cpp ~1032) and `graph.AddPass("Scene", …)` (~1048); the graph executes passes in add order (`RenderGraph::Execute`). The G-buffer's velocity / normal+roughness+metallic / albedo / surface-id are *extra colours of `sceneHDR`* (`velocityIndex`, `normalIndex`, `albedoIndex`, `surfaceIdIndex`, ~487–515), so the direct passes `Sample(sceneHDR)` before the Scene pass writes it -- **there is no precedent for Sample-then-Write of one target in this graph** (no `RGLoad::Load` anywhere; the Scene pass uses `WriteAttachments` + `PreserveDepth`); test it first, and if the graph or the RHI objects, give the G-buffer pass its own target. `rayBudgetMap` is declared at ~1614, *after* the Scene pass, so the trace pass takes no budget-map input in T5 (K per preset, as the design says). `addSignal` and `struct SignalPassNames` live inside the reflection block (~1862–1923) and capture `sceneHDR`, `normalIndex`, `velocityIndex` (all defined by ~515): **hoist the span from `\\t\\t\\tstruct SignalPassNames` to the lambda's closing `\\t\\t\\t};` (the line after `return blurred;`) to just before `const bool gbufferPass = Renderer3D::GBufferPassAvailable();`, one tab out**, and both signals use it.

**How the lit shader gets the two textures -- decided by the RHI's rules.** `VulkanResourceSet::Commit` writes `m_Sets[frame]` in place and **errors if that set was bound earlier in this frame's command buffer** (`WasSetBoundThisFrame`, VulkanPipeline.cpp ~644). Set layouts come from reflection, and an unreferenced sampler is absent from the layout, so `SetTexture` on a binding a pipeline never references is a Vulkan error. Set 3 is taken (the water at 0–8, meshlets at 0–3, every pass's inputs). So: declare `u_DirectDiffuse` / `u_DirectSpecular` at **set 0, bindings 26 and 27** under `#if defined(RV_RAY_SHADOWS) && !defined(RV_TRACE_ONLY) && !defined(RV_GBUFFER) && !defined(RV_TRANSPARENT) && !defined(RV_WATER)` (free bindings today: 20, 26+; 11 is the skinned bone buffer, 7/17 are used). Fill them black in `BeginScene`'s `targets` loop (Renderer3D.cpp ~3958–3966) **for the six lit-kind sets only** -- `Set, SkinnedSet, LayeredSet, MaskedSet, GpuSet, MaskedGpuSet` -- never `TransparentSet/TransparentGpuSet/GBufferSet/MaskedGBufferSet`. Then in `Renderer3D::DrawLit()` (before `DrawLitBody`) set 26/27 to this frame's accumulated pair on those six and `Commit()` each: legal, because in split mode the GBuffer pass binds only `GBufferSet` / `MaskedGBufferSet` / `PrepassSet` (5375–5405) and every lit-kind set is first bound in the Scene pass (`DrawLitBody` 4261+, the meshlet path 4416, the indirect path 4300). `Renderer3D::SetDirectLight(diffuse, specular)` beside `SetWaterLamps` (~6357; members beside `WaterLampDiffuse/Specular` at ~593–596) stores them; the graph calls it before the Scene pass and nulls it after, as it does `SetWaterLamps` (~1396–1402).

**The switch is a uniform, not a define.** `RayRates.w` bit 22 (add `4194304` in the fill at Renderer3D.cpp ~3616–3629 when `config.DirectSignal && K > 0`; the sum stays under 2^24, exact in a float). A preset change then needs no recompile, and the loop's early-out is one uniform branch. `--direct-signal=on|off` is a new `EngineConfig` bool (declare beside `WaterLampPass`, EngineConfig.h ~389; parse beside `"water-lamp-pass"`, EngineConfig.cpp ~407); K is `preset.Lamps` or `--light-sampling=K` exactly as today (~3626).

**The shaders.**
- `pbr_fragment.glsl`: the G-buffer write at ~4096–4102 becomes `o_Albedo = vec4(albedo, clamp(surface.Specular, 0.0, 1.0))` (metallic is already `o_Surface.a`; fix T3's comment) and `o_SurfaceId = v_Instance.y > 0.5 ? -v_ObjectId : v_ObjectId` (sign = Static). `ClusterIndexFor` (1056) reads `v_ClipPos` and sits in a `#ifndef RV_TRACE_ONLY` region (1055–1082): add `ClusterCellAt(vec3 worldPos, vec2 uv)` on the model of `WaterClusterCell` (water_lamps.glsl:157). `IrradianceFieldWeight` (1836), `BakedShare` (288), `LightCullRejects` and `TraceShadowSoftFromMasked` are all available under `RV_TRACE_ONLY`. The loop: guard the `directIrradiance` pre-loop (`float directIrradiance = 0.0;` / `if (mod(u_Scene.ShadowRayFade.x, 16.0) > 4.5)`, ~4203–4206) and, at the loop head after the `RV_WATER` early-out (~4614–4626), skip every positional light that is not a subtractive candidate -- test the 16-byte cull record first (`u_LightCull.Cull[i]`: bit 13 moving-in-range and class ≠ live), never the 80-byte one. Add the textures once, before the single line `vec3 ambientLight = u_Scene.Ambient.rgb * u_Scene.Ambient.a;`: `Lo += diffuseTex.rgb * albedo / PI + specularTex.rgb`.
- `direct_trace.rvshader` (new): the shape of `rtgi_trace.rvshader` -- `RV_TRACE_ONLY` + `pbr_fragment.glsl` + `view_reconstruction.glsl`; set 3: depth, `o_Surface`, `o_Albedo`, `o_SurfaceId`; push block = `GiParams` (NearClip, FarClip, InvP0, InvP1, FlipY, …, CameraRow0-2, CameraPosition; C++ fill at Renderer3D.cpp ~1985–2025) plus K and the frame; two outputs. Reconstruct P as `rtgi_trace` does (`LinearDepth`, `ViewPosition`, the camera rows; the jitter subtracted), N = `OctDecode(surface.rg)`, roughness = `surface.b`, metallic = `surface.a`, albedo/specular from the albedo attachment, static from the id's sign. The in-loop S4 sampler at pbr_fragment.glsl ~4380–4580 is the scoring and reservoir code to lift (target 1: the GGX branch at ~4545–4551); `water_shade.rvshader` ~200–225 is the shade-and-trace of a survivor with the `kind == 0` exemption. Load it like `GiShader` (Renderer3D.cpp ~1573, `traceDefines`), pipeline like `GiPipeline` (~1866–1882; two colour formats), inputs like `GiInputs`; bind `slot.LampSet` at set 0 as every trace-only pass does.
- The contract's second payload (`RV_SIGNAL_PAIR`): `reflection_accumulate.rvshader` gains `u_Fresh2` (set 3 binding 7), `u_History2` (binding 8), `o_Accumulated2` (location 3); `HistoryAt` (274–356) records the texel it took (add `pastTexel` to `Candidate`, ~232–242) so the second payload is read at the same place (`texture` at `pastUv` for k == 0, `texelFetch` otherwise, as `c.past` is); the bound (446–466) needs a second `Neighbourhood` over `u_Fresh2` under the define; the blend at ~500 applies the same `frames`. `reflection_blur.rvshader`: `u_Accumulated2` (binding 4), `o_Blurred2` (location 1), the same weights. C++: the six-pass loops at Renderer3D.cpp ~1540–1570 (load, `diffuseDefines`) and ~3178–3222 (pipelines; `extras` = 2 for accumulate) gain passes 6 and 7 with `RV_SIGNAL_DIFFUSE` + `RV_SIGNAL_PAIR` (accumulate 4 attachments, blur 2); **the six load only `if (s_Data->RayReflectionsOn)` (~1540) -- make it shadows-or-reflections**. `AccumulateSignal` / `BlurSignal` (~6157 / ~6097) take optional `fresh2` / `previous2` and pick the pair pipelines when given. `TemporalHistory::Prepare` (TemporalHistory.cpp) takes three formats -- add a fourth (`m_FourthFormat`, the attachment list, the equality test). `SignalParams` gains nothing for the first landing (one memory for both halves).
- Slots and layers: `TemporalHistory* DirectLight = nullptr;` after `Reflections` in `FrameDesc` (FrameGraphBuilder.h ~138); members beside `m_Reflections` (RuntimeLayer.h:60) and `m_SceneReflections` / `m_GameReflections` (EditorLayer.h:446–447); assignments beside `frame.Reflections = &m_Reflections;` (RuntimeLayer.cpp:313), `scene.Reflections = &m_SceneReflections;` (EditorLayer.cpp:674) and `game.Reflections = &m_GameReflections;` (:819). Prepare it with four formats before the direct block; `Advance()` after the Scene pass as `desc.Reflections->Advance()` is (~1961).
- Debug views: `DirectLight` and `DirectRefusal` in the enum (EngineConfig.h, the three-line `enum class DebugViewMode {…}`), parsed before the `else` warning at EngineConfig.cpp ~761–776; in FrameGraphBuilder.cpp ~3278–3310 the scale (`DirectLight` 4, `DirectRefusal` 6), `auxResource` (the direct history's current target) and `auxAttachment` (0 / 2).
- Counters: `TraceShadowFromMasked` counts every ray (`RV_COUNT_SHADOW_RAY`, ray_shadow_trace.glsl:201), so the new pass's rays land in the shadow lane of `rays per frame` with no work.

**Order to build and check:** (1) the graph plumbing with a trace pass that writes zeros and the lit shader adding them under the switch -- the picture must be black-direct with `--direct-signal=on` and pixel-identical with `off` (that alone proves the set/commit rule and the Sample-then-Write question); (2) the trace pass proper, K = every light (no sampling) -- pixel-identical to the old path for a still frame is the acceptance; (3) the K-sampler; (4) the pair on the contract; (5) the verification list in the design.

"""
assert s.count(anchor) == 1
s = s.replace(anchor, notes.replace('\n', nl) + anchor)
s = rep(s, nl, "| 2b | large | 🔨 IN PROGRESS 2026-09-06: design in §2d (direct light as a signal: one trace pass choosing K lights per pixel, the T4 contract with a second payload, the lit shader adding two textures); building |",
       "| 2b | large | 📝 DESIGN WRITTEN 2026-09-06, NOT BUILT (halted at the usage limit): §2d has the design, the ray-budget answer and the build notes with every anchor; nothing outside docs/ changed. Resume at \"Order to build and check\" |")
save(p, s)

# ---- HANDOFF.md header
p = 'docs/HANDOFF.md'; s, nl = load(p)
old = "**Read this first.** Updated 2026-09-06 (resumed after the halt). The engine is going RT-first: `docs/RT-FIRST.md` is the plan and its §2b table is the ordered list. T1-T4 are done and verified pixel-identical to the accepted state (T4's halt was one stray brace in `reflection_accumulate.rvshader`; §2c records it). **Next is T5 (shadows on the reconstruction contract), on the owner's green signal only** — one task per signal, report after each."
new = "**Read this first.** Updated 2026-09-06 (evening, halted at the usage limit). The engine is going RT-first: `docs/RT-FIRST.md` is the plan and its §2b table is the ordered list. T1-T4 are done and verified pixel-identical to the accepted state (T4's halt was one stray brace in `reflection_accumulate.rvshader`; §2c records it). **T5 (direct light as a signal on the contract) has its design written and NOTHING BUILT** — the owner gave the green signal (\"go for T5, if this affects ray budgeting then let me know\"); §2d holds the design, the ray-budget answer, and the build notes with every file anchor gathered before the halt. Resume at §2d \"Order to build and check\"; the tree outside `docs/` is exactly the T4 state."
assert s.count(old) == 1
s = s.replace(old, new); save(p, s)

# ---- memory
p = r'C:\Users\ism19\.claude\projects\C--Users-ism19-Code\memory\project_ragev_reflection_smear.md'; s, nl = load(p)
old = "**T5 (shadows on the contract) is next, only on the owner's green signal.** RT-FIRST.md §2c has the record.**"
assert s.count(old) == 1
s = s.replace(old, "**T5 (direct light as a signal on the contract): green signal given 2026-09-06, DESIGN WRITTEN in RT-FIRST.md §2d, NOTHING BUILT** -- halted at the usage limit with the build notes (every file anchor, the set-commit rule: set 0 bindings 26/27 re-committed in DrawLit, the uniform switch RayRates.w bit 22, hoist addSignal above the GBuffer pass) recorded in §2d; resume at its \"Order to build and check\". The ray-budget answer for the owner is in §2d too (K per pixel from the preset's Lamps; WR-17 thinning and the S1/S4 instruments go dead for opaque surfaces; the per-tile K lane waits for S3's widening).**")
save(p, s)
p = r'C:\Users\ism19\.claude\projects\C--Users-ism19-Code\memory\MEMORY.md'; s, nl = load(p)
old = "RT-first T1-T4 done and pixel-identical, T5 shadows next on the green signal; "
assert s.count(old) == 1
s = s.replace(old, "RT-first T1-T4 done and pixel-identical; T5 (direct light as a signal) designed in RT-FIRST §2d, not built, resume there; ")
save(p, s)
print('T5 halt notes done')
